<?
$textA1 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textA2 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP nutzen.";

$textA3 = "Sie dürfen den Tarif oder die Tarifoption nicht für Peer to Peer nutzen.";

$textB1 = "Sie haben 50 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$textB2 = "Sie haben 500 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$textC = "Sie haben eine Flat für SMS-Versand in alle deutschen Netze inklusive.";

$textD1 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 300 MB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 7,2 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wenn Sie Ihr Inklusiv-Volumen im Abrechnungszeitraum aufgebraucht haben, wird Ihre Bandbreite auf 32kBit/s beschränkt. Darüber informieren wir Sie per SMS.";

$textD2 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 500 MB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 14,4 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textD3 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 20 GB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textE = "Sie dürfen den Tarif nur als Privatperson nutzen. SMS und MMS dürfen Sie nur manuell über Ihr Endgerät erstellen. Sie dürfen den Tarif nicht weiterverkaufen, nicht unentgeltlich Dritten überlassen und nicht zum Betrieb kommerzieller Dienste nutzen. Die Nutzung in einer stationären Telefonanlage sowie zur Erbringung von Call-Center-Leistungen und für die Kommunikation zwischen Automaten ist unzulässig. Unzulässig ist auch der Aufbau von Verbindungen, bei denen Sie oder Dritte aufgrund der Verbindung Vermögensvorteile erhalten, die von der Dauer der Verbindung abhängen, z.B. Verbindungen zu Werbehotlines.";

$textF = "Die Mindestlaufzeit beträgt 24 Monate, die Kündigungsfrist beträgt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres kündbar. Falls Sie nicht rechtzeitig kündigen, verlängert sich der Vertrag jeweils um ein weiteres Jahr.";

$textG1 = "Falls Sie in einem Abrechnungszeitraum mehr als 15.000 Minuten ins deutsche Vodafone-Mobilfunknetz telefonieren, dürfen wir den Vertrag außerordentlich kündigen.";

$textG2 = "Falls Sie in einem Abrechnungszeitraum mehr als 15000 Minuten in ein deutsches Telekommunikations-Netz telefonieren, dürfen wir den Vertrag außerordentlich kündigen.";

$textH = "Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht über mehrere Karten gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschränkt, die Sie bis auf Weiteres selbst festlegen.";

$textBlack1 = "Sie haben 3000 SMS in alle deutschen Mobilfunknetze inklusive. Für SMS, die darüber hinaus gehen, zahlen Sie 0,19 Euro pro SMS.";

$textBlack2 = "Nach 12 Monaten können Sie ein neues Handy erwerben. Mit Vertragsschluss beginnt erneut eine Mindestlaufzeit von 24 Monaten, die Kündigungsfrist beträgt 3 Monate.";

$textMIFPromoPreis = "Sie können mit dem Tarif auch telefonieren und SMS verschicken. Gespräche in alle deutschen Netze kosten 0,29 Euro pro Minute im 60/60-Takt. SMS in alle deutschen Mobilfunknetze kosten 0,19 Euro pro SMS.";

$textRedFamily = "Sie können eine Vodafone Red Family S zu einem vergünstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red S, Red M, Red L und Red Premium. Die Vodafone Red Family S wird automatisch in den Tarif Vodafone Red S umgestellt, wenn Sie mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 Familienkarten zugeordnet sind.";

$textSmartS = "Sie zahlen 0,09 Euro pro Gesprächsminute bei einem Abrechnungstakt von 60/60.";

$textSmartM = "Ihr Tarif beinhaltet ein Minutenpaket mit 300 Minuten pro Abrechnungszeitraum in alle deutschen Netze. Für Minuten, die über dieses Minutenpaket hinaus gehen, zahlen Sie 0,29 Euro pro Min. Die Abrechung erfolgt im Takt 60/60.";

$textt8a = "Die Mindestlaufzeit beträgt 24 Monate, die Kündigungsfrist beträgt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres kündbar. Wird der Vertrag nicht rechtzeitig gekündigt, verlängert er sich jeweils automatisch um ein weiteres Jahr.";

$textt03 = "Sie dürfen den Tarif nur als Privatkunde nutzen. SMS und MMS dürfen Sie nur manuell über Ihr Endgerät erstellen. Sie dürfen den Tarif nicht weiterverkaufen, nicht unentgeltlich Dritten überlassen und nicht zum Betrieb kommerzieller Dienste nutzen. Die Nutzung in einer stationären Telefonanlage sowie zur Erbringung von Call-Center-Leistungen und für die Kommunikation zwischen Automaten ist unzulässig. Unzulässig ist auch der Aufbau von Verbindungen, bei denen Sie oder Dritte aufgrund der Verbindung Vermögensvorteile erhalten, die von der Dauer der Verbindung abhängen, z.B. Verbindungen zu Werbehotlines.";

$textt38j = "Wird eine SIM Karte in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespräche je deutsches Netz genutzt (Abrechnung minutengenau), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textt38k = "Falls Sie in einem Abrechnungszeitraum mehr als 15.000 Minuten ins deutsche Vodafone-Mobilfunknetz telefonieren, dürfen wir den Vertrag außerordentlich kündigen.";

$textt49d = "Nutzung nur für manuell über das Endgerät erstellte SMS zulässig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3000 SMS hinausgehenden SMS werden gemäß den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textt46b = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textt48l = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 200 MB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 14,4 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05a = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Je DataSIM im Tarif Vodafone Red S zahlen Sie 10 € extra pro Monat und haben 200 MB mehr Datenvolumen in der Übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht über mehrere Karten gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschränkt, die Sie bis auf Weiteres selbst festlegen.";

$textt06 = "Auf Ihrer 1. Rechnung berechnen wir Ihnen den Basispreis für den 1. Vertragsmonat nur anteilig und den Basispreis für den 2. Vertragsmonat im Voraus. In den folgenden Rechnungen sehen Sie dann auch den Basispreis des jeweils nächsten Vertragsmonats. Eventuelle Rabatte ziehen wir jeweils ab. (Kunden im Rahmenvertrag sind hiervon ausgeschlossen.)";

$textt111 = "Die Nutzung für Peer-to-Peer Kommunikation ist nicht gestattet.";

$textt48m = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 500 MB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 21,6 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05b = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Je DataSIM im Tarif Vodafone Red M zahlen Sie 10 € extra pro Monat und haben 500 MB mehr Datenvolumen in der Übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschränkt, die Sie bis auf Weiteres selbst festlegen.";

$textt48n = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 3 GB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05c = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Die 1. DataSIM ist kostenlos. Für die 2. DataSIM im Tarif Vodafone Red L zahlen Sie 10 € extra pro Monat und haben 500 MB mehr Datenvolumen in der Übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschränkt, die Sie bis auf Weiteres selbst festlegen.";

$textt48o = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 10 GB pro Abrechnungszeitraum. Die größtmögliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die nächsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir prüfen während Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser wäre, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschränken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt04a = "Sie können eine Vodafone Red Family S zu einem vergünstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red S, Red M, Red L und Red Premium. Die Vodafone Red Family S wird automatisch in den Tarif Vodafone Red S umgestellt, wenn Sie mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 Familienkarten zugeordnet sind.";

$textt04b = "Sie können eine Vodafone Red Family M zu einem vergünstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red M, Red L und Red Premium. Die Vodafone Red Family M wird automatisch in den Tarif Vodafone Red M umgestellt, wenn Sie  mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 andere Familienkarten zugeordnet sind.";

$textt04c = "Sie können eine Vodafone Red Family L zu einem vergünstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red L und Red Premium. Die Vodafone Red Family L wird automatisch in den Tarif Vodafone Red L umgestellt, wenn Sie mehr als 15000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, Ihre Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 andere Familienkarten zugeordnet sind.";

$textAuftragskopf = "Wenn Sie als Auftraggeber die Vodafone-Karte einem Dritten (=Teilnehmer) zur Nutzung überlassen, können sie neben dem Kundenkennwort auf Wunsch auch ein Teilnehmerkennwort festlegen, das dem Teilnehmer eingeschränkte Möglichkeiten zur Dienstebestellung und Vertragsdatenänderungen einräumt. Den Umfang dieser Möglichkeiten entnehmen Sie bitte einem seperaten Merkblatt, das Ihnen auf Anforderung ausgehändigt wird. Teilnehmerkennwörter für Ihre Vodafone-Karten tragen Sie bitte in die Anlage für Zusatzdienste ein.";

$textAbbuchungserlaubnis1 = "Ich ermächtige Vodafone D2 (VF D2) widerruflich, die Rechnungsbeträge von oben genanntem Konto im Lastschriftverfahren abzubuchen. Die Bedingungen für die Teilnahme am Lastschriftverfahren erkenne ich an. Bei Zuordnung der neuen Vodafone-Karte/n auf ein bereits bestehendes Vodafone-Kundenkonto gilt die hier angegebene Bankverbindung für das gesamte Kundenkonto.";

$textBestaetigt = "Bestätigt: JA";

$textAbbuchungserlaubnis2 = "Ich ermächtige meine kontoführende Bank widerruflich, VF D2 allgemein gehaltene bankübliche Angaben zur Bonitätsprüfung zu erteilen, die im Zusammenhang mit der Inanspruchnahme von VF D2-Dienstleistungen erforderlich sind.";

$textPapierRechnung = "Die zur Verfügungstellung einer Online-Rechnung erfolgt kostenfrei, eine Papierrechnung wird mit monatlich pro Kundenkonto (Preis lt.Preisliste) bepreist.";

$textOnlineRechnung = "Ich verzichte auf die Zusendung von Papierrechnungen und buche stattdessen den Dienst Vodafone-Online Rechnung zu den hierfür geltenden Bedingungen.";

$textTarifMindestlaufzeit = "Die Mindestlaufzeit beträgt 24 Monate, die Kündigungsfrist beträgt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres kündbar. Wird der Vertrag nicht rechtzeitig gekündigt, verlängert er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifWochenendPaketwechsel = "Aus dem von mir gewählten Tarif ist ein Tarifwechsel nur in ein anderes Vodafone-WochenendPaket möglich. Für Wechsel innerhalb der Vodafone-WochenendPakete gilt: Ein wechsel ist in ein Paket mit größerer Anzahl monatlicher Inklusivminuten ist monatlich zum Beginn eines Erfassungszeitraums möglich. Sonstige Wechsel innerhalb der Tarife Vodafone-WochenendPaket 50/100/200/500 sind nur mit einer Frist von 3 Monaten seit Buchung möglich.";

$textTarifKombiWochenendWechsel = "Für Wechsel innerhalb der Vodafone KombiPakete 60/120/240/480/1200 gilt: Ein Wechsel in ein Paket mit größerer Anzahl monatlicher Inklusivminuten ist monatlich zum Beginn eines Erfassungszeitraums möglich. Sonstige Wechsel innerhalb der Tarife KombiPakete 60/120/240/480/1200 sind nur mit einer Frist von 3 Monaten seit Buchung möglich. Im übrigen sind Tarifwechsel ausgeschlossen.";

$textTarifDatentarife = "Ein Wechsel in einen anderen Datentarif ist während der Mindestlaufzeit nicht möglich.";

$textTarifEinzugsermaechtigung = "Nur mit Einzugsermächtigung";

$textTarifMinutenpaketWechsel = "Aus dem von mir gewählten Tarif ist ein Wechsel in enien Tarif mit niedrigerem monatlichen Basispreis bzw. Paketpreis erstmals 3 Monate nach erfolgter Einrichtung möglich. Ein wechsel in einen Tarif mit höheren Basispreis bzw. Paketpreis ist jederzeit möglich. Im Übrigen ergeben sich die Wechselmöglichkeiten und -konditionen aus der Preisliste.";

$textTarifSimOnlyMinutenpaketWechsel = "Tarifwechsel innerhalb der Vodafone MinutenPakete SIM only sind jederzeit möglich, bei Wechsel in ein Vodafone MinutenPaket SIMonly mit weniger monatlichen inklusivminuten jedoch erstmalig nach drei Monaten. Tarifwechsel in Tarife, die bei erstmaligem Abschluss zum gleichzeitigen Erwerb eines vergünstigen Mobiltelefons berechtigen, sind nur bei gleichzeitiger Verlängerung der Mindestlaufzeit des Vertrages auf 24 Monate. Im Übrigen sind Tarifwechsel ausgeschlossen.";

$textTarifZuhauseTalk24 = "Sonderbedingungen/Leistungsumfang: Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für den Tarif Vodafone Zuhause FestnetzFlat folgende Besonderheiten:
a) Die Festnetznummer muss dem Vorwahlbereich entstammen, der der Zuhause-Adresse des Kunden entspricht. Bei späterer Änderung der Zuhause-Adresse wird dem Kunden von Vodafone D2 bei Bedarf eine neue Festnetznummer zugeteilt.
b) Die Nutzung des VF D2-Netzes ist - vorbehaltlich der Regelung in c) - räumlich auf die Zuhause-Adresse beschränkt ('regionale Nutzung'). Diese Beschränkung wird VF D2 innerhalb der ersten 5 Tage nach Vertragsabschluss einrichten; die bis dahin mögliche deutschlandweite Nutzung wird bei Inanspruchnahme zu den für die regionale Nutzung geltenden Preisen abgerechnet.
c) Abgehende Verbindungen zur Vodafone-KundenBetreuung (1216) und Notruf (112, 110) können abweichend von b) bis auf weiteres im Bereich
der von VF D2 national betriebene Funkstation in Anspruch genommen werden. VF D2 behält sich vor, die Inanspruchnahme dieser Leistungen
ebenfalls auf die regionale Nutzung zu begrenzen.
d) In seinem ZuhauseBereich ist der Kunde unter seiner Festnetz-Nummer erreichbar, sobald die Portierung von seinem bisherigen Vertragspartner des Festnetzanschlusses durchgeführt wurde; die Portierung erfolgt zum im Rahmen des bisherigen Vertrages nächstmöglichen Kündigungstermin im Auftrag von Vodafone D2 zu BT (Germany) GmbH & Co. OHG. Bis zur erfolgreichen Portierung kann der Kunde 'Vodafone Zuhause mit Festnetznummer' für abgehende Verbindungen uneingeschränkt nutzen. Ziffer 4.8 der AGB für Vodafone D2-Dienstleistungen über die Abwicklung einer Portierung von Vodafone D2 zu einem anderen Anbieter findet für Festnetz-Nummern keine Anwendung; bei Beendigung des Vertrages mit Vodafone D2 fällt die Festnetznummer des Kunden an den ursprünglich ausgebenden Netzbetreiber zurück, sofern der Kunde zuvor keine Portierung über einen neuen Anbieter beauftragt hat und diese rechtzeitig bei Vodafone D2 eingegangen ist.
e) International Roaming (Nutzung der Vodafone-Karte im Ausland) ist ausgeschlossen. Dem Kunden steht eine Vodafone-Mailbox zur Verfügung,
eine ProfiMailbox kann nicht eingerichtet werden. Mit Vodafone Zuhause stehen die Übertragungstechnologien GPRS und UMTS nicht zur
Verfügung. Damit ist auch die Nutzung der auf diesen Technologien beruhenden Dienste - z.B. MMS, Videotelefonie, Logos, Klingeltöne,
Ring-up-Tones, MeinAdressbuch usw.- ausgeschlossen.
f) Die Anbindung des Tarifs erfolgt über das Vodafone-Mobilfunknetz.
g) Die Registrierung der Festnetz-Nummer für Telefonbucheintrag und Auskunft kann erst nach Vertragsabschluss und erfolgreicher Portierung
erfolgen; hierzu wird dem Kunden ein Auftragsformular zugesandt. Bei abgehenden Verbindungen erfolgt keine Anzeige der Festnetz-Nummer als
Absenderkennung, es wird ausschließlich die Mobilfunk-Nummer des Kunden übermittelt, sofern die Rufnummernunterdrückung vom Kunden
nicht aktiviert wurde.";


$textTarifZuhauseTaktung = "Für Verbindungen mit Vodafone Zuhause ins Dt. Festnetz gilt immer die 60/60-Taktung, auch wenn für ihren Mobilfunktarif im Übrigen eine andere Taktung  vereinbart ist.";

$textTarifZuhauseBedingungH= "Sonderbedingungen/Leistungsumfang: Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für \"die Vodafone Zuhause-Funktionalität\" folgende Besonderheiten zum Leistungsumfang:\na) Vodafone D2 teilt dem Kunden zusätzlich zu seiner Vodafone-Mobilfunknummer eine neue Festnetznummer aus dem Vorwahlbereich zu, der seiner jeweils aktuellen zuhause-Adresse entspricht. Die Zuteilung dieser Festnetznummer erfolgt spätestens innerhalb von 6 Wochen nach Antrag des Kunden.\nb) Die Nutzung von \"Vodafone Zuhause\" ist räumlich auf die festgelegte Zuhause-Adresse beschränkt. Den ZuhauseBereich wird Vodafone D2 innerhalb von 5 Tagen nach Beauftragung einrichten. Vodafone D2 erfasst bei jeder Verbindung zu Abrechnungszwecken, ob sich der Kunde innerhalb oder außerhalb des ZuhauseBereichs aufhält. Die Abrechnung zu \"Vodafone Zuhause\"-Konditionen wird jeweils durch einen Signalton zu Beginn eines jeden Gespräches angezeigt (Die zusätzlich visuelle Information im Display des Mobiltelefons wird nicht von allen Endgeräten unterstützt). Weitergehende Möglichkeiten und Konditionen des Vodafone Anruf Manager siehe Preisliste.\nc) Die Zubuchung einer Karte in einem Tarif \"Vodafone ZuhauseTalk oder -Talk24 (Zusatz zu Laufzeitvertrag)\" zu vergünstigten Konditionen ist nicht möglich.";


$textTarifSuperFlat = "Der Kunde darf die Vodafone-Karte ausschließlich als Endkunde im dafür  und nur zum Aufbau manuell über das Mobilfunkendgerät gewählter Verbindungen nutzen; unzulässig ist die Nutzung zum Betrieb von mehrwert- und Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center-Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationsdienstleistungen für Dritte, zur Weitervermittlung von Mobilfunkteilnehmern im Vodafone-bnetz oder in andere Netze über die Vodafone-Karte sowie zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in Abhängigkeit von der Dauer der Verbingung Zahlungen der andere vermögenswerte Gegenleistungen Dritter erhält (z.B. Verbindungen zu Werbehotlines).";

$textTarifSuperFlatNF ="Wird eine Sim Karte in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespräche in das dt. Vodafone Netz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textTarifSuperFlatFV= "Wird eine SIM Karte in einem Abrechnungszeitraum mehr als insgesamt je 15.000 Minuten für nationale Standardgespräche ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textTarifSuperFlatNV= "Wird eine Sim Karte in einem Abrechnugnszeitraum mehr als 15.000 Minuten für nationale Standardgespräche in das dt. Vodafonenetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textTarifSuperFlatWE= "Wird eine Sim Karte im Tarif Vodafone SuperFlat Wochenende SIMonly/Vodafone SuperFlat WOchenende in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespräche am WOchenende (Samstag und SOnntag) ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textTarifSuperFlatWE_NEW= "Die Vodafone-Tarife SUperFlat Wochenende und SUperFlat Wochenende mit Handy-5 beinhalten zusätzlich einen monatlichen Mindestumsatz von 5,00 Euro für nicht in der SUperFlat WOchenende enthaltene Leistungen gemäß Preisliste. Der Mindestumsatz wird auf Telefonate aus dem deutschen Vodafone-Netz in alle deutschen Netze angerechnet, ausgenommen sind Konferenzverbindungen und SOnderrufnummern. Der Mindestumsatz wird ebenfalls auf SMS und MMS aus dem deutschen Vodafone Netz in alle deutschen Netze angerechnet, ausgenommen sind Sondernummern und SMS über MeinVodafone im Internet. Gebuchte Minuten- und/oder Messaging-Optionen werden nicht mit dem Mindestumsatz verrechnet, eine Anrechnung erfolgt dann ab Überschreiten der zugebuchten Leistungen.";

$textTarifSuperFlatWE_NEW2= "Wird eine SIM Karte im Tarif Vodafone SuperFlat Wochenende SIMonly/Vodafone SuperFlat Wochenende in einem Abrechnungszeitraum mehr als je 15.000 Minuten für nationale Standardgespräche am Wochenende (Samstag und Sonntag) ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverhältnis außerordentlich zu kündigen.";

$textTarifSuperFlatTK= "Die Einbringung der SIM-Karte in eine stationäre Telefonanlage, die Nutzung zur Erbringung von CallCenter-Leistungen sowie eine Nutzung für die Kommunikation zwischen Automaten sind unzulässig. Unzulässig ist ferner der Aufbau von Verbindungen, bei denen der Kunde oder ein Dritter aufgrund der Verbindung von der Dauer der Verbindung abhängige Vermögesnvorteile erhält (z.B. Verbindungen zu Werbehotlines).";

$textTarifInternetSMS="Nutzung nur für manuell über das Endgerät erstellte SMS zulässig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3.000 SMS hinausgehenden SMS werden gemäß den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifInternetDV="Nutzung nur für manuell über das Endgerät erstellte SMS zulässig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3000 SMS hinausgehenden SMS werden gemäß den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textSMSInfoundPreis = "Sie haben 3000 SMS in alle deutschen Mobilfunknetze inklusive. Für SMS, die darüber hinaus gehen, zahlen Sie 0,19 Euro pro SMS.";

$textTarifInternetNutzung="Der Kunde darf d. Vodafone-Karte ausschließlich als Endkunde im dafür und nur für Verbindugnen, die manuell über die Hardware aufgebaut werden nutzen. Eine Weiterveräußerung sowie unentgeltliche Überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzulässig. Bis zu einem Datenvolumen von 500 MB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verfügbare Bandbreite bereitgestellt, ab 500 MB stehen max. 64 kbit/s zur Verfügung. Vodafone behält sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuführen.";

$textTarifInternetVOIP="Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textMCSNutzungsverhalten="Ergibt sich, dass es aufgrund des Nutzungsverhaltens des Kunden für diesen in einem Rechnugnszyklus günstiger gewesen wäre, wenn er eine Inklusivvolumen (Vodafone Mobile Connect Volume L / Vodafone Mobile COnnect Flat) gewählt hätte, so wird für die Berechnung im akteullen Rechnungszyklus sowie für die weitere Vertragslaufzeit die für den Kunden im Referenzzeitraum günstige DAtentarifoption zugrunde gelegt. Der Kunde kann innerhalb von vier Wochen nach ERhalt der Mitteilung über die Umstellung der automatischen Festlegung widersprechen und eine der oberen genannten Tarifoptionen wählen. MAcht der Kunde von seinem Widerspruchsrecht keinen Gebrauch, so ist nach Ablauf der Widerspruchsfrist ein WEchsel während der Mindestlaufzeit in eine Datentarifoption mit geringerem monatlichen Paketpreis nicht möglich. Die Minstestlaufzeit der eingereichten Tarifoption richtet sich nach der Mindestlaufzeit des zugrunde liegenden Vertrages im Tarif Vodafone Mobile Connect Sofort.";

$textMCSVertragsbestand="Wenn der Vodafone Zuhause DSL Vertrag nicht mehr besteht, wird der Tarif 'Vodafone MObile COnnect Sofort' durch den Tarif 'Vodafone Mobile Connect Starter' ersetzt.";

$textMCSVertragsbestand2="Für die zu dem Tarif ztubuchbaren Datentarifoptionen 'Vodafone Mobile Connect Colume L' und 'Vodafone MObile Connect Flat' gelten die VOrzugspreise ebenfalls nur solange ein Vodafone Zuhause DSL Vertrag besteht.";

$tarivMCSVertragsbestand3="Der Tarif 'Vodafone Mobile Connect Sofort' kann nur von Kunden beauftragt werden, die bereits das Vodafone Zuhause DSL All-Inclusive-Paket gebucht haben. Pro DSL All-Inclusive-Paket darf nur ein Vertrag im Tarif 'Vodafone Mobile Connect Sofort' bestehen.";

$tarifMCFNutzung="Nutzung nur als Endkunde im dafür ; kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5GB im geweiligen Abrechnugnszeitraum wird die jeweils aktuell maximal verfügbare Bandbreite bereitgestellt; ab 5 GB stehen max. 64 kBit/s zur Verfüfung.";

$textVerbindungsübersicht = "Soweit eine Verbindungsübersicht beauftragt ist (s. Anlage für Zusatzdienste), werde ich Mitbenutzer gemäß Ziff. 9.3 der AGB für VF D2-Dienstleistungen auf die Speicherung und Mitteilung der Verbindungsdaten hinweisen. Ziff. 9 der AGB für VF D2-Dienstleistungen zum Umfang der Speicherung von Verbindungsdaten (auch ohne Verbindungübersichten) habe ich zur Kenntnis genommen.";

$textWerbebereitschaft = "\n[X] Ja, ich möchte über Leistungen und Tarife von Vodafone* informiert werden. Vodafone* darf meine Bestandsdaten zum Zweck der Beratung, Marktforschung und Werbung für Vodafone*-Angebote verarbeiten und nutzen und meine Verkehrsdaten (Zeitpunkt, Dauer und Zielgasse) zur bedarfsgerechten Gestaltung für längstens sechs Monate verwenden\n[X] Ja, Vodafone darf mich telefonisch und per SMS/MMS kontaktieren und über Vodafone-Angebote beraten. Ich kann diese Einwilligung jederzeit ganz oder teilweise für die Zukunft widerrufen.\n\n*Vodafone D2 GmbH und Vodafone AG & Co. KG.\nDie Daten dürfen zwischen den beiden Unternehmen zu den vorgenannten Zwecken wechselseitig übermittelt werden.\n 
Hinweis: Ohne die vorstehende Einwilligung ist Vodafone im Rahmen der gesetzlichen Bestimmungen lediglich berechtigt, Ihnen Werbung für eigene Angebote per Text- oder Bildmitteilung an Ihr Telefon, per E-Mail an Ihre elektronische Postadresse und per Post an Ihre Anschrift zukommen zu lassen. Sie können der Nutzung Ihrer Telefonnummer und Adressen zu diesem Zwecke jederzeit schriftlich oder elektronisch widersprechen.\n\n
Datum: ".$Date. 
"\nUnterschrift des                      X\nAuftraggebers:                        ____________________________\nName in Druckbuchstaben:    ".$enti[Ansprechpartner]."\n\n";

$textBeauftragung = "\n1. Auftrag für Vodafone D2-Dienstleistungen: Bestandteil des Vertrages sind die Allgemeinen Geschäftsbedingungen und die Preisliste für Vodafone D2 Dienstleistungen.\nHinweis: Die Allgemeinen Geschäftsbedingungen für Vodafone D2 Dienstleistungen hängen in den Verkaufsräumen aus.\n2. Begrenzung der monatilichen Entgelthöhe: Mir ist bekannt, dass eine Begrenzung der monatlichen Entgelthöhe (§ 18 Telekommunikations-Kundenschutzverordnung) während der gesamten Vertragslaufzeit nicht möglich ist, sondern nur im Rahmen eines CallYa-Mobilfunkvertrages realisiert werden kann. \n3. SCHUFA/Auskunfteien: Ich willige in den Datenaustausch mit der SCHUFA-Gesellschaft und den sonstigen Auskunfteien gem. Ziff. 11 der AGB für Vodafone D2-Dienstleistungen ein.\n\n
Datum: ".$Date. 
"\nUnterschrift des                      X\nAuftraggebers:                        ____________________________\nName in Druckbuchstaben:    ".$enti[Ansprechpartner]."\n\n";

$textVodafoneNummer = "Soweit möglich, bitte ich um Zuteilung der in der Anlage für Zusatzdienste aufgeführten Vodafone-Nummer(n). Mir ist bekannt, dass die Zuteilung dieser Rufnummer(n) durch VF D2 nicht zugesichert werden kann und daher nicht Voraussetzung für das Zustandekommen des Vertrages ist. Die formale Zuteilung meiner Vodafone-Nummer(n) erfolgt mit der ersten Rechnung.";

$textTarifVodafoneMobileInternetFlat50 = "Nutzung nur als Endkunde im dafür üblichen Umfang im dt. Vodafone Mobilfunk-Netz; kein Weiterverkauf, keine Überlassung and Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 20 GB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verfügbare Bandbreite Ihres Tarifs von bis zu 50 mbit/s bereitgestellt; ab 20 GB stehen max. 64 kbit/s zur Verfügung.";

$textTarifVodafoneMobileInternetFlat51 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textTarifVodafoneMobileInternetFlat52 = "Wir behalten uns vor, die Verbindung nach je 24 Stunden automatisch zu trennen. Am Ende jeder Verbindung, mindestens aber nach 24 Stunden, runden wir auf den nächsten 100-KB-Block auf.";

$textTarifVodafoneMobileInternetFlat53 = "Mindestlaufzeit des Tarifes: 24 Monate, Kündigungsfrist: 3 Monate; der Tarif ist erstmalig zum Ende der Mindestlaufzeit kündbar; wird nicht (rechtzeitig) gekündigt, verlängert er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifVodafoneMobileInternetFlat1 = "Mindestlaufzeit des Tarifes: 24 Monate, Kündigungsfrist: 3 Monate; der Tarif ist erstmalig zum Ende der Mindestlaufzeit kündbar; wird nicht (rechtzeitig) gekündigt, verlängert sie/er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifVodafoneMobileInternetFlat2 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textTarifVodafoneMobileInternetFlat336 = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verfügbare Bandbreite Ihres Tarifs von bis zu 3,2 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verfügung.";

$textTarifVodafoneMobileInternetFlat372 = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verfügbare Bandbreite Ihres Tarifs von bis zu 7,2 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verfügung.";

$textTarifVodafoneMobileInternetFlat3144 = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verfügbare Bandbreite Ihres Tarifs von bis zu 14,4 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verfügung.";

$textTarifVodafoneMobileInternetFlat3216 = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verfügbare Bandbreite Ihres Tarifs von bis zu 21,6 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verfügung.";

$textTarifVodafoneMobileInternetFlat4 = "Da das LTE Zuhause Internet Paket mit der von mir gewünschten Bandbreite nicht zur Verfügung steht, bin ich damit einverstanden, dass das gewünschte Paket mit einer geringeren Bandbreite, jedoch mit dem vereinbarten Inklusiv-Datenvolumen / Monat zur Verffügung gestellt wird.";

$textTarifVodafoneMobileInternetFlat5 = "Der Wechsel in einen SIMonly Tarif ist während der Mindestlaufzeit nicht möglich.";

$textTarifVodafoneMobileInternetFlat72Promo = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Die MobileInternet Flat 7,2 Promo enthält unbegrenztes Datenübertragungsvolumen im deutschen Vodafone-Netz. Bis zu einem Datenvolumen von 1 GB steht Ihnen im jeweiligen Abrechnungszeitraum die aktuell maximal verfügbare Bandbreite von bis zu 7,2 Mbit/s zur Verfügung, danach max. 64 Kbit/s.";

$textTarifVodafoneMobileInternetFlat216Promo = "Nutzung nur als Endkunde im dafür üblichen Umfang: kein Weiterverkauf, keine Überlassung an Dritte; kein Betrieb kommerzieller Dienste. Die MobileInternet Flat 21,6 Promo enthält unbegrenztes Datenübertragungsvolumen im deutschen Vodafone-Netz. Bis zu einem Datenvolumen von 3 GB steht Ihnen im jeweiligen Abrechnungszeitraum die aktuell maximal verfügbare Bandbreite von bis zu 21,6 Mbit/s zur Verfügung, danach max. 64 Kbit/s.";

$textTarifMIFAPN = "Bei einem MobileInternet-Tarif oder einer MobileInternet-Option gilt Ihr Inklusiv-Volumen nur für den APN web.vodafone.de und nur im deutschen Vodafone-Mobilfunknetz.";

$textDienstZuhauseFlatrate1 = "Die Mindestlaufzeit beträgt 3 Monate. Die Kündigungsfrist beträgt 2 Wochen. Die Option ist erstmalig zum Ablauf der Mindestlaufzeit kündbar. Wird die Option nicht rechtzeitig gekündigt, verlängert sich die Option jeweils automatisch um drei Monate. Bei Buchung mit Vodafone KombiComfort filt im Hinblick auf die Mindestlaufzeit der Tarifoption abweichend: DIe Mindestlaufzeit beträgt 24 Monate. Die Kündigungsfrist beträgt 3 Monate. Die Option ist erstmalig zum Ende der Mindestlaufzeit kündbar. Wird die Option nicht rechtzeitig gekündigt, verlängert sie sich geweils automatisch um 12 Monate. Die Tarifoption endet automatisch mit Beendigung der Vodafone ZuhauseOption oder des Vodafone-Vertrages über die Hauptkarte.";

$textDienstZuhauseFlatrate2 = "Die Tarifoption Vodafone ZuhauseFlatrate und -HappyInternational gelten nicht für Rufumleitungen und Konferenzverbindungen. Der Kunde darf die Vodafone-Karte ausschließlich als Endkunde im dafür  und nur zum Aufbau manuell über das Mobilfunkendgerät gewählter Verbindungen nutzen; unzulässig ist insbesondere die Nutzung zum Betrieb von Mehrwert- oder Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center-Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationdiesnstleistungen für Dritte, zur Weitervermittlung von mobilfunkteilnehmern im Vodafone-Netz oder in andere netze über die Vodafone-Karte und zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in Abhängingkeit von der Dauert der Verbundung Zahlungen oder andere vermögenswerte Gegendienstleistungen Dritter erhält (z.B. Verbindungen zu Werbehotlines).";

$textDienstZuhauseOption1 = "Für Verbindugnen mit der Vodafone ZuhauseOption ins dt. Festnetz gilt immer die 60/60 Taktung, auch wenn für Ihren Mobilfunktarif im Übrigen eine andere Taktung vereinbart ist.";

$textDienstZuhauseOption2 = "Die Mindestlaufzeit beträgt 2 Wochen. Die Option ist erstmalig zum Ablauf der Mindwestlaufzeit kündbar. Wird die Iotion nicht rechtzeitig gekündigt, verlängert sich die Option jeweils automatisch um drei Monate. Die Tarifoption endet automatisch mit Beendigung des Vodafone-Vertrages über die Hauptkarte. Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für die \"Vodafone Zuhause-Funktionalität\" folgende Vesonderheiten zum Leisuntsumfang:\na) Vodafone D2 teilt dem Kunden zusätzluich zu seiner Vodafone-Mobilfunknummer eine neue Festnetznummer aus dem Vorwahlbereich zu, der seiner jeweils aktuellen Zuhause-adresse entspricht. Die Zuteilung dieser Festnetznummer erfolgt spätestens innerhalb von 6 Wochen nach Antrag des Kunden.\nb) Die Nutzung von \"Vodafone Zuhause\" ist räumlich auf die festgelegte Zuhause-Adresse beschränkt. Den ZuhauseBereich wird Vodafone D2 innerhalb von 5 Tagen nach Beauftragung einrichen. Vodafone D2 erfasst bei jeder Verbindung zu Abrechnungszwecken, ob sich der Kunde innerhalb oder außerhalb des Zuhause Bereichs aufhält. Die Abrechnung zu \"Vodafone Zuhause\" -Konditionen wird jeweils durch einen Signalton zu Beginn eines jeden Gespräches angezeigt (Die zusätzliche visuelle Information im Display des Mobiltelefons wird nicht von allen Endgeräten unterstütz).\nc) Pro Hauptkarte in einem Tarif mit Mindestlaufzeit kann nur eine Karte in einem Tarif \"Vodafone ZuhauseTalk (Zusatz zu Laufzeitvertrag)\" zugebucht werden; die Hauptkarte darf keinem Großkundenrahmenvertrag zugeordnet sein und kenier sonstigen Rabattvereinbarung unterliegen.";

$textDienstHappyInternational1 = "Die Tarifoptionen Vodafone ZuhauseFlatrate und -HappyInternational gelten nicht für Rufumleitungen und Konferenzverbindungen. Der Kunde darf die Vodafone-Karte ausschließlich als Endkunde im dafür üblichen Umfang und nur zum Aufbau manuell über das Mobilfunkengerät gewählter Verbindungen nutzen; unzulässig ist insbesondere die Nutzung zum Betrieb von Mehrwert- oder Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center.Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationsdienstleistungen für Dritte, zur WEitervermittlung von Mobilfunkteilnehmern im Vodafone-Netz oder in andere Netze über die Vodafone-Karte und zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in abhängigkeit von der Dauer der Verbindungs Zahlungem oder ander vermögenswerte Gegenleistungen Dritter erhält (z.b. Verbindungen zu Werbehotlines).";

$textDienstHappyInternational2 = "Die Tarifoption Vodafone HappyInternational (\"HappyInternational\") setzt zu jedem Zeitpunkt einen Vodafone-Kundenvertrag einschließlich der Tarifoption Vodafone Zuhause Option und Vodafone Zuhause Flatrate oder einen Vodafone Kundenvertrag in einem der Tarife Vodafone SuperFlat, -SuperFlat(SIM Only) oder -Zuhause Talk24 voraus. Die Mindestlaufzeit von happyInternational beträgt 24 Monate; sofern der Vodafone-Kundenvertrag bei Buchung von HappyInternational eine kürzere verbleibende Mindestlaufzeit als 24 Monate aufweist, verkürzt sich die Mindestlaufzeit von HappyInternational au fden gleichen Zeitraum. Wird die Mindestlaufzeit des Vodafone-Kundenvertrages verlängert, verlängert sich die Mindestlaufzeit von HappyInternational entsprechend. HappyInternational ist erstmalig zum Ende der jeweiligen Mindestlaufzeit kündbar. Wird HappyInternational nicht (rechtzeitig) gekündigt, verlängert es sich jeweils automatisch um ein Jahr.";

$textDienstHappyWochenendeAbend = "Zusätzlicher monatlicher Paketpreis/Aufpreis gemäß Preisliste für Vodafone-MinutenPakete. Die Mindestlaufzeit der Option beträgt 3 Monate; die Kündigungsfrist 2 Wochen. Die Option ist erstamals zum Ende der Mindestlaufzeit kündbar. Wird nicht (rechtzeitig) gekündigt, verlängert sich die Option automatisch jeweils um 1 Monat.";

$textDienstSmsFremdnetzPaket = "Zusätzlicher monatlicher Paketpreis/Aufpreis gemäß Preisliste für Vodafone-MinutenPakete.";

$textDienstHappyLiveBroadband = "Vertragsbestandteil ist die Tarifoption Happy Live! Broadband. Der monatliche Basispreis erhöht sich dadurch um 2,50 Euro monatlich gegenüber dem in der Preisliste zum heweiligen gebuchten Tarif ausgewiesenen monatlichen Basispreis. Dies gilt auch im Fall eines oder mehrerer Tarifwechsel nach Tarifoptionen. Die Kündigungsfrist für die Tarifoption HappyLive! Broadband beträgt 3 monate, die Mindestlaufzeit 24 Monate, beginnend mit der Unterzeichnung dieses Auftrages. Die Tarifoption ist erstmals zum Ende der Mindestlaufzeit kündbar. Wird die Tarifoption nicht (rechtzeitig) gekündigt, verlängert sie sich jeweils automatisch um einen Monat. Der Erhöhungsbetrag wird auf der Rechnung gesondert ausgewiesen.";

$textDienstMusikPaket = "Mtl. Paketpreis 10 EUR für 10 Music-Downloads und 1 Std. RadioDJ (minutengenaue Abrechnung bei Channel- o. Collectionwechsel u. am Verbindungsende). Nicht genutzte Inklusivleistungen sind jeweils nicht in den Folgemonat übertragbar. Die Dienste sind nur im Vodafone live!-Portal mit f. d. Dienst geeignetem Handy nutzbar. Die Mindestlaufzeit der Tarifoption/des Zusatzdienstes beträgt 24 Monate, die Kündigungsfrist 2 Wochen. Die Tarifoption/ der Zusatzdienst ist erstmals zum Ende der Mindestlaufzeit kündbar. Wird nicht gekündigt, verlängert sich die Tarifoption/ der Zusatzdienst jeweils um einen weiteren Monat.";

$textDienstWebContentTime1 = "Bei vorhandener HSDPA-Versorgung und HSDPA fähigem Endgerät ist HSDPA bis 31.07.2007 ohne zusätzliche Berechnung nutzbar. Danach werden für eine HSDPA-Freischaltung 5,00 EUR/Monat berechnet. Eine Voice-over-IP-Nutzung wird ab dem 08.07.2007 technisch unterbunden.";

$textDienstWebContentTime2 = "Die Mindestvertragslaufzeit der Tarifoption/ des Zusatzdienstes beträgt 24 Monate, die Kündigungsfrist 3 Monate. Die Tarifoptio/ der Zusatzdienst ist erstmalig zum Ende der Mindestlaufzeit kündbar. Wird nicht gekündigt, verlängert sich die Tarifoption/ der Zusatzdienst jeweils um ein weiteres Jahr.";

$textDienstStudentenrabatt = "Der Studenten-Vorteil wird nur gewährt, sofern und solange die folgenden Voraussetzungen erfüllt sind:\n- Eine aktuelle Legitimationsbescheinigung (= deutsche Immatrikulationsbescheinigung, deutscher Studentenausweis, deutscher Schülerausweis einer allgemeinbildenden oder Berufschule, deutscher Wehr- oder Ersatzdienstausweis oder deutscher Ausweis über die Teilnahme an einem freiwilligen sozialen Jahr) wird Vodafone bei Vertragsabschluß vorgelegt.\n- Das Alter beträgt maximal 30 Jahre.\n- EIne Lastschrift-Einzugsermächtigung wird erteilt.\n- Es liegt kein sonstiger mobilfunkvertrag mit Studenten-Konditionen bei einem Mobilfunkanbieter im Vodafone D2-Netz vor.\n- Die Vodafone-Karte darf keinem Großkundenrahmenvertrag zugeordnet sein und keiner sonstigen Rabattvereinbarung unterliegen.\nDer Studenten- Vorteil wird für folgende Dauer gewährt:\n- Für Wehrpflichtige, Zivildienstleistende und Absolventeneines freiwilligen sozialen Jahres max. 1 Jahr\n- im Übrigen solange die oben genannten Voraussetzungen erfüllt bleiben und eine aktuelle Legitimationsbescheinigung jährlich vorgelegt wird.\nMir ist bekannt, dass eine automatische Umstellung der Vodafone-Karte in den von mir gewählten Ausgangstarif ohne Studenten-Vorteil erfolgt, wenn eine der oben genannten Voraussetzungen nicht vorliegt oder später entfällt oder wenn der Vertrag über die Vodafone-karte auf eine andere Person übertragen wird.\nDie Konditionen des Studenten-Vorteils ergeben sich ergänzend zu der Preisliste für Vodafone-Tarife aus dem Tarif-Flyer Studenten-Rabatt.\n\nLegitimation für Studenten-Rabatt:\n Ort der (Hoch-)Schule/Tätigkeit:   $enti[StudentOrt] \n Geburtsdatum:                       $enti[StudentGeburtsdatum] ";

$text200MB = "Der Kunde darf d. Vodafone-Karte ausschließlich als Endkunde im dafür üblichen Umfang und nur für Verbindungen, die manuell über die Hardware aufgebaut werden, nutzen. Eine Weiterveräußerung sowie unentgeltliche Überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzulässig. Bis zu einem Datenvolumen von 200 MB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verfügbare Bandbreite bereitgestellt, ab 200 MB stehen max. 64 kbit/s zur Verfügung. Vodafone behält sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuführen.";

$textZHFNTarifwechsel = "Tarifwechsel in andere Mobilfunktarife sind ausgeschlossen.";

$textPrivatnutzungKarte = "Sie dürfen als Kunde die Vodafone-Karte ausschließlich als Privatkunde im dafür üblichen Umfang und nur für Verbindungen, die manuell über die Hardware aufgebaut werden, nutzen. Eine Weiterveräußerung sowie unentgeltliche Überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzulässig. Beim Surfen im deutschen Vodafone-Netz auf http-basierten Internet-Seiten (über die APN wap.vodafone.de und web.vodafone.de.), fällt ein Preis von 0,19 Euro pro MB an. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf den nächsten 100 KBBlock auf. Die maximal verfügbare Bandbreite ist 7,2 MBit/s. Vodafone prüft ab Einrichtung des Tarifes während Ihrer Vertragslaufzeit, ob eine zusätzliche Datenoption für Ihr Nutzungsverhalten günstiger wäre und richtet diese mit einer monatlichen Laufzeit für Sie ein. Vodafone informiert Sie darüber per SMS. Vodafone behält sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuführen.";

$textTarifSuper100SMS = "Nutzung nur für manuell über das Endgerät erstellte SMS zulässig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 100 SMS hinausgehenden SMS werden gemäß den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifSuper50SMS = "Nutzung nur für manuell über das Endgerät erstellte SMS zulässig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 50 SMS hinausgehenden SMS werden gemäß den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifSuperDatenvolumen = "Die Nutzung des inklusiven Datenvolumens ist nur mit Handy gestattet. Für die Nutzung mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computers gilt das inklusive Datenvolumen nicht, diese wird gemäß ihrem Tarif berechnet.";

$textDienstBILDplusDigital = " Vodafone BILDplus DIGITAL Promo24
• Zugang zu Nachrichten von BILDplus Digital und Bundesliga bei BILD
• 500 MB Highspeed-Volumen zusätzlich inklusive
• Nach 24 Monaten endet der Zugang zu BILDplus Digital und Bundesliga bei BILD sowie das 500 MB Highspeed-Volumen automatisch
• Inhaltlich verantwortlich für BILDplus Digital und Bundesliga bei Bild Nachrichten und die Applikation selbst ist die Axel Springer AG, es gelten die Bedingungen der Axel Springer AG. Das Angebot erfolgt im Namen und Rechnung von Vodafone";

$textDienstDatenOptionM = "Die Tarifoption hat eine Mindestlaufzeit von 24 Monaten, die aber spätestens mit der Mindestlaufzeit des zugrunde liegenden Vodafone-Vertrags endet.Das Inklusiv-Datenvolumenbeträgt 200 MB im jeweiligen Abrechnungszeitraum, bei Nutzung über 200 MB hinaus fällt ein Preis von 2,50 Euro pro 50 MB-Block an. Die maximal verfügbare Bandbreite ist 7,2 Mbit/s. Vodafone behält sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuführen.Sie dürfen die Tarifoption nur mit Ihrem internetfähigen Handy nutzen. Mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computer dürfen Sie die Tarifoption nicht nutzen. Sie dürfen die Tarifoption nicht für Voice over IP, Instant Messaging und Peer to Peer nutzen. Durch den zugrunde liegenden Vodafone-Vertrag entstehen weitere Kosten.";

$textDienstDatenOptionS = "Die Tarifoption hat eine Mindestlaufzeit von 24 Monaten, die aber spätestens mit der Mindestlaufzeit des zugrunde liegenden Vodafone-Vertrags endet. Das Inklusiv-Datenvolumenbeträgt 50 MB im jeweiligen Abrechnungszeitraum, bei Nutzung über 50 MB hinaus fällt ein Preis von 0,19 Euro pro MB an. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf den nächsten 100 KB-Block auf. Die maximal verfügbare Bandbreite ist 7,2 Mbit/s. Vodafone prüft ab Einrichtung des Tarifes während Ihrer Vertragslaufzeit, ob eine zusätzliche Datenoption für Ihr Nutzungsverhalten günstiger wäre und richtet diese mit einer monatlichen Laufzeit für Sie ein. Vodafone informiert Sie darüber per SMS. Vodafone behält sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuführen.Sie dürfen die Tarifoption nur mit Ihrem internetfähigen Handy nutzen. Mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computer dürfen Sie die Tarifoption nicht nutzen. Sie dürfen die Tarifoption nicht für Voice over IP, Instant Messaging und Peer to Peer nutzen. Durch den zugrunde liegenden Vodafone-Vertrag entstehen weitere Kosten.";

$textBlackBerryInternet = "Sie haben 50 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$basic100sim1 = "mtl. Paketpreis 14,99 € für 24 Monate, danach mtl. 19,99€. Mindestlaufzeit 24 Monate, einmalige Anschlusskosten 29,99 €.";

$basic100sim2 = "Tarif enthält 100 Min. in alle dt. Netze und ins dt. Festnetz sowie 100 SMS in alle dt. Netze. Beim Surfen im dt. Vodafone-Netz steht Ihnen ein Inklusiv-Datenvolumen von 200 MB/Monat (statt regulär 100 MB) zur Verfügung. Bei Nutzung bis 200 MB pro Abrechnungszeitraum steht Ihnen eine Bandbreite von bis zu 7,2 MBit/s zur Verfügung, danach bis zu 64 KBit/s.";

$basic100sim3 = "Für Nutzung über Inklusiv-Leistungen hinaus ggf. weitere Kosten je nach Verbrauch, z. B. Standardgespräche in dt. Mobilfunknetze 0,29 €/Min. (60/60-Takt) oder 0,19 €/Standard-SMS.";

$basic100sim4 = "Tethering, Voice-over-IP- und Peer-to-Peer-Kommunikation nicht gestattet.";

$basic100sim5 = "Nicht verbrauchte Inklusiv-Leistungen nicht in den Folgemonat übertragbar.";

?>