<?
$textA1 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textA2 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP nutzen.";

$textA3 = "Sie dürfen den Tarif oder die Tarifoption nicht für Peer to Peer nutzen.";

$textB1 = "Sie haben 50 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$textB2 = "Sie haben 500 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$textC = "Sie haben eine Flat für SMS-Versand in alle deutschen Netze inklusive.";

$textD1 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 300 MB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 7,2 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wenn Sie Ihr Inklusiv-Volumen im Abrechnungszeitraum aufgebraucht haben, wird Ihre Bandbreite auf 32kBit/s beschr�nkt. Darüber informieren wir Sie per SMS.";

$textD2 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 500 MB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 14,4 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textD3 = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 20 GB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textE = "Sie dürfen den Tarif nur als Privatperson nutzen. SMS und MMS dürfen Sie nur manuell über Ihr Endger�t erstellen. Sie dürfen den Tarif nicht weiterverkaufen, nicht unentgeltlich Dritten überlassen und nicht zum Betrieb kommerzieller Dienste nutzen. Die Nutzung in einer station�ren Telefonanlage sowie zur Erbringung von Call-Center-Leistungen und für die Kommunikation zwischen Automaten ist unzul�ssig. Unzul�ssig ist auch der Aufbau von Verbindungen, bei denen Sie oder Dritte aufgrund der Verbindung Verm�gensvorteile erhalten, die von der Dauer der Verbindung abh�ngen, z.B. Verbindungen zu Werbehotlines.";

$textF = "Die Mindestlaufzeit betr�gt 24 Monate, die K�ndigungsfrist betr�gt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres k�ndbar. Falls Sie nicht rechtzeitig k�ndigen, verl�ngert sich der Vertrag jeweils um ein weiteres Jahr.";

$textG1 = "Falls Sie in einem Abrechnungszeitraum mehr als 15.000 Minuten ins deutsche Vodafone-Mobilfunknetz telefonieren, dürfen wir den Vertrag au�erordentlich k�ndigen.";

$textG2 = "Falls Sie in einem Abrechnungszeitraum mehr als 15000 Minuten in ein deutsches Telekommunikations-Netz telefonieren, dürfen wir den Vertrag au�erordentlich k�ndigen.";

$textH = "Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht über mehrere Karten gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschr�nkt, die Sie bis auf Weiteres selbst festlegen.";

$textBlack1 = "Sie haben 3000 SMS in alle deutschen Mobilfunknetze inklusive. Für SMS, die darüber hinaus gehen, zahlen Sie 0,19 Euro pro SMS.";

$textBlack2 = "Nach 12 Monaten können Sie ein neues Handy erwerben. Mit Vertragsschluss beginnt erneut eine Mindestlaufzeit von 24 Monaten, die K�ndigungsfrist betr�gt 3 Monate.";

$textMIFPromoPreis = "Sie können mit dem Tarif auch telefonieren und SMS verschicken. Gespr�che in alle deutschen Netze kosten 0,29 Euro pro Minute im 60/60-Takt. SMS in alle deutschen Mobilfunknetze kosten 0,19 Euro pro SMS.";

$textRedFamily = "Sie können eine Vodafone Red Family S zu einem verg�nstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red S, Red M, Red L und Red Premium. Die Vodafone Red Family S wird automatisch in den Tarif Vodafone Red S umgestellt, wenn Sie mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 Familienkarten zugeordnet sind.";

$textSmartS = "Sie zahlen 0,09 Euro pro Gespr�chsminute bei einem Abrechnungstakt von 60/60.";

$textSmartM = "Ihr Tarif beinhaltet ein Minutenpaket mit 300 Minuten pro Abrechnungszeitraum in alle deutschen Netze. Für Minuten, die über dieses Minutenpaket hinaus gehen, zahlen Sie 0,29 Euro pro Min. Die Abrechung erfolgt im Takt 60/60.";

$textt8a = "Die Mindestlaufzeit betr�gt 24 Monate, die K�ndigungsfrist betr�gt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres k�ndbar. Wird der Vertrag nicht rechtzeitig gek�ndigt, verl�ngert er sich jeweils automatisch um ein weiteres Jahr.";

$textt03 = "Sie dürfen den Tarif nur als Privatkunde nutzen. SMS und MMS dürfen Sie nur manuell über Ihr Endger�t erstellen. Sie dürfen den Tarif nicht weiterverkaufen, nicht unentgeltlich Dritten überlassen und nicht zum Betrieb kommerzieller Dienste nutzen. Die Nutzung in einer station�ren Telefonanlage sowie zur Erbringung von Call-Center-Leistungen und für die Kommunikation zwischen Automaten ist unzul�ssig. Unzul�ssig ist auch der Aufbau von Verbindungen, bei denen Sie oder Dritte aufgrund der Verbindung Verm�gensvorteile erhalten, die von der Dauer der Verbindung abh�ngen, z.B. Verbindungen zu Werbehotlines.";

$textt38j = "Wird eine SIM Karte in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespr�che je deutsches Netz genutzt (Abrechnung minutengenau), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textt38k = "Falls Sie in einem Abrechnungszeitraum mehr als 15.000 Minuten ins deutsche Vodafone-Mobilfunknetz telefonieren, dürfen wir den Vertrag au�erordentlich k�ndigen.";

$textt49d = "Nutzung nur für manuell über das Endger�t erstellte SMS zul�ssig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3000 SMS hinausgehenden SMS werden gem�� den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textt46b = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textt48l = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 200 MB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 14,4 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05a = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Je DataSIM im Tarif Vodafone Red S zahlen Sie 10 � extra pro Monat und haben 200 MB mehr Datenvolumen in der übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht über mehrere Karten gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschr�nkt, die Sie bis auf Weiteres selbst festlegen.";

$textt06 = "Auf Ihrer 1. Rechnung berechnen wir Ihnen den Basispreis für den 1. Vertragsmonat nur anteilig und den Basispreis für den 2. Vertragsmonat im Voraus. In den folgenden Rechnungen sehen Sie dann auch den Basispreis des jeweils n�chsten Vertragsmonats. Eventuelle Rabatte ziehen wir jeweils ab. (Kunden im Rahmenvertrag sind hiervon ausgeschlossen.)";

$textt111 = "Die Nutzung für Peer-to-Peer Kommunikation ist nicht gestattet.";

$textt48m = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 500 MB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 21,6 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05b = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Je DataSIM im Tarif Vodafone Red M zahlen Sie 10 � extra pro Monat und haben 500 MB mehr Datenvolumen in der übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschr�nkt, die Sie bis auf Weiteres selbst festlegen.";

$textt48n = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 3 GB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt05c = "Sie können zu Ihrer Vodafone-Hauptkarte mit Vertragslaufzeit 2 DataSIMs buchen. Die 1. DataSIM ist kostenlos. Für die 2. DataSIM im Tarif Vodafone Red L zahlen Sie 10 � extra pro Monat und haben 500 MB mehr Datenvolumen in der übertragungsgeschwindigkeit Ihres zugrunde liegenden Tarifs. Hauptkarte und DataSIMs haben eine gemeinsame Rufnummer, eine gemeinsame Rechnung und eine gemeinsame Mailbox. Sie können keine Verbindungen von DataSIM zu DataSIM herstellen und keine Vodafone-Services mit Festnetz-Nummer nutzen, wie z.B. Vodafone Zuhause oder Vodafone Office. Sie können nicht gleichzeitig Services derselben Kategorie nutzen, also z.B. jemanden anrufen oder identische Datendienste nutzen. Das Versenden und Empfangen von SMS und MMS ist auf eine Karte beschr�nkt, die Sie bis auf Weiteres selbst festlegen.";

$textt48o = "Fürs Surfen im deutschen Vodafone-Netz über wap.vodafone.de und web.vodafone.de haben Sie ein Inklusiv-Volumen von 10 GB pro Abrechnungszeitraum. Die gr��tm�gliche Bandbreite ist 100 Mbit/s. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf die n�chsten 100 KB auf. Wir behalten uns vor, die Verbindung nach 24 Stunden automatisch zu trennen. Wir pr�fen w�hrend Ihrer Vertragslaufzeit, ob eine Datenoption für Sie besser w�re, behalten uns vor, diese mit einer monatlichen Laufzeit für Sie einzurichten oder Ihre Bandbreite auf 32 kBit/s zu beschr�nken, wenn Sie Ihr Inklusiv-Volumen verbraucht haben. Darüber informieren wir Sie per SMS.";

$textt04a = "Sie können eine Vodafone Red Family S zu einem verg�nstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red S, Red M, Red L und Red Premium. Die Vodafone Red Family S wird automatisch in den Tarif Vodafone Red S umgestellt, wenn Sie mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 Familienkarten zugeordnet sind.";

$textt04b = "Sie können eine Vodafone Red Family M zu einem verg�nstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red M, Red L und Red Premium. Die Vodafone Red Family M wird automatisch in den Tarif Vodafone Red M umgestellt, wenn Sie  mehr als 15.000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, die Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 andere Familienkarten zugeordnet sind.";

$textt04c = "Sie können eine Vodafone Red Family L zu einem verg�nstigten Preis pro Monat zu diesen Tarifen buchen: Vodafone Red L und Red Premium. Die Vodafone Red Family L wird automatisch in den Tarif Vodafone Red L umgestellt, wenn Sie mehr als 15000 Minuten ins deutsche Festnetz telefonieren, den Vertrag zu Ihrer Hauptkarte beenden, Ihre Hauptkarte in einen Rahmenvertrag aufgenommen wird oder der Hauptkarte schon 4 andere Familienkarten zugeordnet sind.";

$textAuftragskopf = "Wenn Sie als Auftraggeber die Vodafone-Karte einem Dritten (=Teilnehmer) zur Nutzung überlassen, können sie neben dem Kundenkennwort auf Wunsch auch ein Teilnehmerkennwort festlegen, das dem Teilnehmer eingeschr�nkte M�glichkeiten zur Dienstebestellung und Vertragsdaten�nderungen einr�umt. Den Umfang dieser M�glichkeiten entnehmen Sie bitte einem seperaten Merkblatt, das Ihnen auf Anforderung ausgeh�ndigt wird. Teilnehmerkennw�rter für Ihre Vodafone-Karten tragen Sie bitte in die Anlage für Zusatzdienste ein.";

$textAbbuchungserlaubnis1 = "Ich erm�chtige Vodafone D2 (VF D2) widerruflich, die Rechnungsbetr�ge von oben genanntem Konto im Lastschriftverfahren abzubuchen. Die Bedingungen für die Teilnahme am Lastschriftverfahren erkenne ich an. Bei Zuordnung der neuen Vodafone-Karte/n auf ein bereits bestehendes Vodafone-Kundenkonto gilt die hier angegebene Bankverbindung für das gesamte Kundenkonto.";

$textBestaetigt = "Best�tigt: JA";

$textAbbuchungserlaubnis2 = "Ich erm�chtige meine kontof�hrende Bank widerruflich, VF D2 allgemein gehaltene bank�bliche Angaben zur Bonit�tspr�fung zu erteilen, die im Zusammenhang mit der Inanspruchnahme von VF D2-Dienstleistungen erforderlich sind.";

$textPapierRechnung = "Die zur Verf�gungstellung einer Online-Rechnung erfolgt kostenfrei, eine Papierrechnung wird mit monatlich pro Kundenkonto (Preis lt.Preisliste) bepreist.";

$textOnlineRechnung = "Ich verzichte auf die Zusendung von Papierrechnungen und buche stattdessen den Dienst Vodafone-Online Rechnung zu den hierfür geltenden Bedingungen.";

$textTarifMindestlaufzeit = "Die Mindestlaufzeit betr�gt 24 Monate, die K�ndigungsfrist betr�gt 3 Monate. Der Vertrag ist, sofern nicht Abweichendes vereinbart ist, erstmals zum Ablauf des zweiten Vertragsjahres k�ndbar. Wird der Vertrag nicht rechtzeitig gek�ndigt, verl�ngert er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifWochenendPaketwechsel = "Aus dem von mir gew�hlten Tarif ist ein Tarifwechsel nur in ein anderes Vodafone-WochenendPaket m�glich. Für Wechsel innerhalb der Vodafone-WochenendPakete gilt: Ein wechsel ist in ein Paket mit gr��erer Anzahl monatlicher Inklusivminuten ist monatlich zum Beginn eines Erfassungszeitraums m�glich. Sonstige Wechsel innerhalb der Tarife Vodafone-WochenendPaket 50/100/200/500 sind nur mit einer Frist von 3 Monaten seit Buchung m�glich.";

$textTarifKombiWochenendWechsel = "Für Wechsel innerhalb der Vodafone KombiPakete 60/120/240/480/1200 gilt: Ein Wechsel in ein Paket mit gr��erer Anzahl monatlicher Inklusivminuten ist monatlich zum Beginn eines Erfassungszeitraums m�glich. Sonstige Wechsel innerhalb der Tarife KombiPakete 60/120/240/480/1200 sind nur mit einer Frist von 3 Monaten seit Buchung m�glich. Im �brigen sind Tarifwechsel ausgeschlossen.";

$textTarifDatentarife = "Ein Wechsel in einen anderen Datentarif ist w�hrend der Mindestlaufzeit nicht m�glich.";

$textTarifEinzugsermaechtigung = "Nur mit Einzugserm�chtigung";

$textTarifMinutenpaketWechsel = "Aus dem von mir gew�hlten Tarif ist ein Wechsel in enien Tarif mit niedrigerem monatlichen Basispreis bzw. Paketpreis erstmals 3 Monate nach erfolgter Einrichtung m�glich. Ein wechsel in einen Tarif mit h�heren Basispreis bzw. Paketpreis ist jederzeit m�glich. Im �brigen ergeben sich die Wechselm�glichkeiten und -konditionen aus der Preisliste.";

$textTarifSimOnlyMinutenpaketWechsel = "Tarifwechsel innerhalb der Vodafone MinutenPakete SIM only sind jederzeit m�glich, bei Wechsel in ein Vodafone MinutenPaket SIMonly mit weniger monatlichen inklusivminuten jedoch erstmalig nach drei Monaten. Tarifwechsel in Tarife, die bei erstmaligem Abschluss zum gleichzeitigen Erwerb eines verg�nstigen Mobiltelefons berechtigen, sind nur bei gleichzeitiger Verl�ngerung der Mindestlaufzeit des Vertrages auf 24 Monate. Im �brigen sind Tarifwechsel ausgeschlossen.";

$textTarifZuhauseTalk24 = "Sonderbedingungen/Leistungsumfang: Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für den Tarif Vodafone Zuhause FestnetzFlat folgende Besonderheiten:
a) Die Festnetznummer muss dem Vorwahlbereich entstammen, der der Zuhause-Adresse des Kunden entspricht. Bei sp�terer �nderung der Zuhause-Adresse wird dem Kunden von Vodafone D2 bei Bedarf eine neue Festnetznummer zugeteilt.
b) Die Nutzung des VF D2-Netzes ist - vorbehaltlich der Regelung in c) - r�umlich auf die Zuhause-Adresse beschr�nkt ('regionale Nutzung'). Diese Beschr�nkung wird VF D2 innerhalb der ersten 5 Tage nach Vertragsabschluss einrichten; die bis dahin m�gliche deutschlandweite Nutzung wird bei Inanspruchnahme zu den für die regionale Nutzung geltenden Preisen abgerechnet.
c) Abgehende Verbindungen zur Vodafone-KundenBetreuung (1216) und Notruf (112, 110) können abweichend von b) bis auf weiteres im Bereich
der von VF D2 national betriebene Funkstation in Anspruch genommen werden. VF D2 beh�lt sich vor, die Inanspruchnahme dieser Leistungen
ebenfalls auf die regionale Nutzung zu begrenzen.
d) In seinem ZuhauseBereich ist der Kunde unter seiner Festnetz-Nummer erreichbar, sobald die Portierung von seinem bisherigen Vertragspartner des Festnetzanschlusses durchgef�hrt wurde; die Portierung erfolgt zum im Rahmen des bisherigen Vertrages n�chstm�glichen K�ndigungstermin im Auftrag von Vodafone D2 zu BT (Germany) GmbH & Co. OHG. Bis zur erfolgreichen Portierung kann der Kunde 'Vodafone Zuhause mit Festnetznummer' für abgehende Verbindungen uneingeschr�nkt nutzen. Ziffer 4.8 der AGB für Vodafone D2-Dienstleistungen über die Abwicklung einer Portierung von Vodafone D2 zu einem anderen Anbieter findet für Festnetz-Nummern keine Anwendung; bei Beendigung des Vertrages mit Vodafone D2 f�llt die Festnetznummer des Kunden an den urspr�nglich ausgebenden Netzbetreiber zur�ck, sofern der Kunde zuvor keine Portierung über einen neuen Anbieter beauftragt hat und diese rechtzeitig bei Vodafone D2 eingegangen ist.
e) International Roaming (Nutzung der Vodafone-Karte im Ausland) ist ausgeschlossen. Dem Kunden steht eine Vodafone-Mailbox zur Verf�gung,
eine ProfiMailbox kann nicht eingerichtet werden. Mit Vodafone Zuhause stehen die übertragungstechnologien GPRS und UMTS nicht zur
Verf�gung. Damit ist auch die Nutzung der auf diesen Technologien beruhenden Dienste - z.B. MMS, Videotelefonie, Logos, Klingelt�ne,
Ring-up-Tones, MeinAdressbuch usw.- ausgeschlossen.
f) Die Anbindung des Tarifs erfolgt über das Vodafone-Mobilfunknetz.
g) Die Registrierung der Festnetz-Nummer für Telefonbucheintrag und Auskunft kann erst nach Vertragsabschluss und erfolgreicher Portierung
erfolgen; hierzu wird dem Kunden ein Auftragsformular zugesandt. Bei abgehenden Verbindungen erfolgt keine Anzeige der Festnetz-Nummer als
Absenderkennung, es wird ausschlie�lich die Mobilfunk-Nummer des Kunden übermittelt, sofern die Rufnummernunterdr�ckung vom Kunden
nicht aktiviert wurde.";


$textTarifZuhauseTaktung = "Für Verbindungen mit Vodafone Zuhause ins Dt. Festnetz gilt immer die 60/60-Taktung, auch wenn für ihren Mobilfunktarif im �brigen eine andere Taktung  vereinbart ist.";

$textTarifZuhauseBedingungH= "Sonderbedingungen/Leistungsumfang: Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für \"die Vodafone Zuhause-Funktionalit�t\" folgende Besonderheiten zum Leistungsumfang:\na) Vodafone D2 teilt dem Kunden zus�tzlich zu seiner Vodafone-Mobilfunknummer eine neue Festnetznummer aus dem Vorwahlbereich zu, der seiner jeweils aktuellen zuhause-Adresse entspricht. Die Zuteilung dieser Festnetznummer erfolgt sp�testens innerhalb von 6 Wochen nach Antrag des Kunden.\nb) Die Nutzung von \"Vodafone Zuhause\" ist r�umlich auf die festgelegte Zuhause-Adresse beschr�nkt. Den ZuhauseBereich wird Vodafone D2 innerhalb von 5 Tagen nach Beauftragung einrichten. Vodafone D2 erfasst bei jeder Verbindung zu Abrechnungszwecken, ob sich der Kunde innerhalb oder au�erhalb des ZuhauseBereichs aufh�lt. Die Abrechnung zu \"Vodafone Zuhause\"-Konditionen wird jeweils durch einen Signalton zu Beginn eines jeden Gespr�ches angezeigt (Die zus�tzlich visuelle Information im Display des Mobiltelefons wird nicht von allen Endger�ten unterst�tzt). Weitergehende M�glichkeiten und Konditionen des Vodafone Anruf Manager siehe Preisliste.\nc) Die Zubuchung einer Karte in einem Tarif \"Vodafone ZuhauseTalk oder -Talk24 (Zusatz zu Laufzeitvertrag)\" zu verg�nstigten Konditionen ist nicht m�glich.";


$textTarifSuperFlat = "Der Kunde darf die Vodafone-Karte ausschlie�lich als Endkunde im dafür  und nur zum Aufbau manuell über das Mobilfunkendger�t gew�hlter Verbindungen nutzen; unzul�ssig ist die Nutzung zum Betrieb von mehrwert- und Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center-Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationsdienstleistungen für Dritte, zur Weitervermittlung von Mobilfunkteilnehmern im Vodafone-bnetz oder in andere Netze über die Vodafone-Karte sowie zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in Abh�ngigkeit von der Dauer der Verbingung Zahlungen der andere verm�genswerte Gegenleistungen Dritter erh�lt (z.B. Verbindungen zu Werbehotlines).";

$textTarifSuperFlatNF ="Wird eine Sim Karte in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespr�che in das dt. Vodafone Netz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textTarifSuperFlatFV= "Wird eine SIM Karte in einem Abrechnungszeitraum mehr als insgesamt je 15.000 Minuten für nationale Standardgespr�che ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textTarifSuperFlatNV= "Wird eine Sim Karte in einem Abrechnugnszeitraum mehr als 15.000 Minuten für nationale Standardgespr�che in das dt. Vodafonenetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textTarifSuperFlatWE= "Wird eine Sim Karte im Tarif Vodafone SuperFlat Wochenende SIMonly/Vodafone SuperFlat WOchenende in einem Abrechnungszeitraum mehr als 15.000 Minuten für nationale Standardgespr�che am WOchenende (Samstag und SOnntag) ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textTarifSuperFlatWE_NEW= "Die Vodafone-Tarife SUperFlat Wochenende und SUperFlat Wochenende mit Handy-5 beinhalten zus�tzlich einen monatlichen Mindestumsatz von 5,00 Euro für nicht in der SUperFlat WOchenende enthaltene Leistungen gem�� Preisliste. Der Mindestumsatz wird auf Telefonate aus dem deutschen Vodafone-Netz in alle deutschen Netze angerechnet, ausgenommen sind Konferenzverbindungen und SOnderrufnummern. Der Mindestumsatz wird ebenfalls auf SMS und MMS aus dem deutschen Vodafone Netz in alle deutschen Netze angerechnet, ausgenommen sind Sondernummern und SMS über MeinVodafone im Internet. Gebuchte Minuten- und/oder Messaging-Optionen werden nicht mit dem Mindestumsatz verrechnet, eine Anrechnung erfolgt dann ab überschreiten der zugebuchten Leistungen.";

$textTarifSuperFlatWE_NEW2= "Wird eine SIM Karte im Tarif Vodafone SuperFlat Wochenende SIMonly/Vodafone SuperFlat Wochenende in einem Abrechnungszeitraum mehr als je 15.000 Minuten für nationale Standardgespr�che am Wochenende (Samstag und Sonntag) ins dt. Vodafone- und Festnetz genutzt (Abrechnung in 60/1 Taktung), ist Vodafone berechtigt, das Vertragsverh�ltnis au�erordentlich zu k�ndigen.";

$textTarifSuperFlatTK= "Die Einbringung der SIM-Karte in eine station�re Telefonanlage, die Nutzung zur Erbringung von CallCenter-Leistungen sowie eine Nutzung für die Kommunikation zwischen Automaten sind unzul�ssig. Unzul�ssig ist ferner der Aufbau von Verbindungen, bei denen der Kunde oder ein Dritter aufgrund der Verbindung von der Dauer der Verbindung abh�ngige Verm�gesnvorteile erh�lt (z.B. Verbindungen zu Werbehotlines).";

$textTarifInternetSMS="Nutzung nur für manuell über das Endger�t erstellte SMS zul�ssig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3.000 SMS hinausgehenden SMS werden gem�� den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifInternetDV="Nutzung nur für manuell über das Endger�t erstellte SMS zul�ssig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 3000 SMS hinausgehenden SMS werden gem�� den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textSMSInfoundPreis = "Sie haben 3000 SMS in alle deutschen Mobilfunknetze inklusive. Für SMS, die darüber hinaus gehen, zahlen Sie 0,19 Euro pro SMS.";

$textTarifInternetNutzung="Der Kunde darf d. Vodafone-Karte ausschlie�lich als Endkunde im dafür und nur für Verbindugnen, die manuell über die Hardware aufgebaut werden nutzen. Eine Weiterver�u�erung sowie unentgeltliche überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzul�ssig. Bis zu einem Datenvolumen von 500 MB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verf�gbare Bandbreite bereitgestellt, ab 500 MB stehen max. 64 kbit/s zur Verf�gung. Vodafone beh�lt sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuf�hren.";

$textTarifInternetVOIP="Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textMCSNutzungsverhalten="Ergibt sich, dass es aufgrund des Nutzungsverhaltens des Kunden für diesen in einem Rechnugnszyklus g�nstiger gewesen w�re, wenn er eine Inklusivvolumen (Vodafone Mobile Connect Volume L / Vodafone Mobile COnnect Flat) gew�hlt h�tte, so wird für die Berechnung im akteullen Rechnungszyklus sowie für die weitere Vertragslaufzeit die für den Kunden im Referenzzeitraum g�nstige DAtentarifoption zugrunde gelegt. Der Kunde kann innerhalb von vier Wochen nach ERhalt der Mitteilung über die Umstellung der automatischen Festlegung widersprechen und eine der oberen genannten Tarifoptionen w�hlen. MAcht der Kunde von seinem Widerspruchsrecht keinen Gebrauch, so ist nach Ablauf der Widerspruchsfrist ein WEchsel w�hrend der Mindestlaufzeit in eine Datentarifoption mit geringerem monatlichen Paketpreis nicht m�glich. Die Minstestlaufzeit der eingereichten Tarifoption richtet sich nach der Mindestlaufzeit des zugrunde liegenden Vertrages im Tarif Vodafone Mobile Connect Sofort.";

$textMCSVertragsbestand="Wenn der Vodafone Zuhause DSL Vertrag nicht mehr besteht, wird der Tarif 'Vodafone MObile COnnect Sofort' durch den Tarif 'Vodafone Mobile Connect Starter' ersetzt.";

$textMCSVertragsbestand2="Für die zu dem Tarif ztubuchbaren Datentarifoptionen 'Vodafone Mobile Connect Colume L' und 'Vodafone MObile Connect Flat' gelten die VOrzugspreise ebenfalls nur solange ein Vodafone Zuhause DSL Vertrag besteht.";

$tarivMCSVertragsbestand3="Der Tarif 'Vodafone Mobile Connect Sofort' kann nur von Kunden beauftragt werden, die bereits das Vodafone Zuhause DSL All-Inclusive-Paket gebucht haben. Pro DSL All-Inclusive-Paket darf nur ein Vertrag im Tarif 'Vodafone Mobile Connect Sofort' bestehen.";

$tarifMCFNutzung="Nutzung nur als Endkunde im dafür ; kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5GB im geweiligen Abrechnugnszeitraum wird die jeweils aktuell maximal verf�gbare Bandbreite bereitgestellt; ab 5 GB stehen max. 64 kBit/s zur Verf�fung.";

$textVerbindungsübersicht = "Soweit eine Verbindungsübersicht beauftragt ist (s. Anlage für Zusatzdienste), werde ich Mitbenutzer gem�� Ziff. 9.3 der AGB für VF D2-Dienstleistungen auf die Speicherung und Mitteilung der Verbindungsdaten hinweisen. Ziff. 9 der AGB für VF D2-Dienstleistungen zum Umfang der Speicherung von Verbindungsdaten (auch ohne Verbindungübersichten) habe ich zur Kenntnis genommen.";

$textWerbebereitschaft = "\n[X] Ja, ich m�chte über Leistungen und Tarife von Vodafone* informiert werden. Vodafone* darf meine Bestandsdaten zum Zweck der Beratung, Marktforschung und Werbung für Vodafone*-Angebote verarbeiten und nutzen und meine Verkehrsdaten (Zeitpunkt, Dauer und Zielgasse) zur bedarfsgerechten Gestaltung für l�ngstens sechs Monate verwenden\n[X] Ja, Vodafone darf mich telefonisch und per SMS/MMS kontaktieren und über Vodafone-Angebote beraten. Ich kann diese Einwilligung jederzeit ganz oder teilweise für die Zukunft widerrufen.\n\n*Vodafone D2 GmbH und Vodafone AG & Co. KG.\nDie Daten dürfen zwischen den beiden Unternehmen zu den vorgenannten Zwecken wechselseitig übermittelt werden.\n 
Hinweis: Ohne die vorstehende Einwilligung ist Vodafone im Rahmen der gesetzlichen Bestimmungen lediglich berechtigt, Ihnen Werbung für eigene Angebote per Text- oder Bildmitteilung an Ihr Telefon, per E-Mail an Ihre elektronische Postadresse und per Post an Ihre Anschrift zukommen zu lassen. Sie können der Nutzung Ihrer Telefonnummer und Adressen zu diesem Zwecke jederzeit schriftlich oder elektronisch widersprechen.\n\n
Datum: ".$Date. 
"\nUnterschrift des                      X\nAuftraggebers:                        ____________________________\nName in Druckbuchstaben:    ".$enti[Ansprechpartner]."\n\n";

$textBeauftragung = "\n1. Auftrag für Vodafone D2-Dienstleistungen: Bestandteil des Vertrages sind die Allgemeinen Gesch�ftsbedingungen und die Preisliste für Vodafone D2 Dienstleistungen.\nHinweis: Die Allgemeinen Gesch�ftsbedingungen für Vodafone D2 Dienstleistungen h�ngen in den Verkaufsr�umen aus.\n2. Begrenzung der monatilichen Entgelth�he: Mir ist bekannt, dass eine Begrenzung der monatlichen Entgelth�he (� 18 Telekommunikations-Kundenschutzverordnung) w�hrend der gesamten Vertragslaufzeit nicht m�glich ist, sondern nur im Rahmen eines CallYa-Mobilfunkvertrages realisiert werden kann. \n3. SCHUFA/Auskunfteien: Ich willige in den Datenaustausch mit der SCHUFA-Gesellschaft und den sonstigen Auskunfteien gem. Ziff. 11 der AGB für Vodafone D2-Dienstleistungen ein.\n\n
Datum: ".$Date. 
"\nUnterschrift des                      X\nAuftraggebers:                        ____________________________\nName in Druckbuchstaben:    ".$enti[Ansprechpartner]."\n\n";

$textVodafoneNummer = "Soweit m�glich, bitte ich um Zuteilung der in der Anlage für Zusatzdienste aufgef�hrten Vodafone-Nummer(n). Mir ist bekannt, dass die Zuteilung dieser Rufnummer(n) durch VF D2 nicht zugesichert werden kann und daher nicht Voraussetzung für das Zustandekommen des Vertrages ist. Die formale Zuteilung meiner Vodafone-Nummer(n) erfolgt mit der ersten Rechnung.";

$textTarifVodafoneMobileInternetFlat50 = "Nutzung nur als Endkunde im dafür �blichen Umfang im dt. Vodafone Mobilfunk-Netz; kein Weiterverkauf, keine überlassung and Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 20 GB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verf�gbare Bandbreite Ihres Tarifs von bis zu 50 mbit/s bereitgestellt; ab 20 GB stehen max. 64 kbit/s zur Verf�gung.";

$textTarifVodafoneMobileInternetFlat51 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textTarifVodafoneMobileInternetFlat52 = "Wir behalten uns vor, die Verbindung nach je 24 Stunden automatisch zu trennen. Am Ende jeder Verbindung, mindestens aber nach 24 Stunden, runden wir auf den n�chsten 100-KB-Block auf.";

$textTarifVodafoneMobileInternetFlat53 = "Mindestlaufzeit des Tarifes: 24 Monate, K�ndigungsfrist: 3 Monate; der Tarif ist erstmalig zum Ende der Mindestlaufzeit k�ndbar; wird nicht (rechtzeitig) gek�ndigt, verl�ngert er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifVodafoneMobileInternetFlat1 = "Mindestlaufzeit des Tarifes: 24 Monate, K�ndigungsfrist: 3 Monate; der Tarif ist erstmalig zum Ende der Mindestlaufzeit k�ndbar; wird nicht (rechtzeitig) gek�ndigt, verl�ngert sie/er sich jeweils automatisch um ein weiteres Jahr.";

$textTarifVodafoneMobileInternetFlat2 = "Sie dürfen den Tarif oder die Tarifoption nicht für Voice over IP und Peer to Peer nutzen.";

$textTarifVodafoneMobileInternetFlat336 = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verf�gbare Bandbreite Ihres Tarifs von bis zu 3,2 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verf�gung.";

$textTarifVodafoneMobileInternetFlat372 = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verf�gbare Bandbreite Ihres Tarifs von bis zu 7,2 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verf�gung.";

$textTarifVodafoneMobileInternetFlat3144 = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verf�gbare Bandbreite Ihres Tarifs von bis zu 14,4 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verf�gung.";

$textTarifVodafoneMobileInternetFlat3216 = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Bis zu einem Datenvolumen von 5 GB im jeweiligen Abrechungszeitraum wird jeweils die aktuell maximal verf�gbare Bandbreite Ihres Tarifs von bis zu 21,6 mbit/s bereitgestellt; ab 5 GB stehen max 64 kbit/s zur Verf�gung.";

$textTarifVodafoneMobileInternetFlat4 = "Da das LTE Zuhause Internet Paket mit der von mir gew�nschten Bandbreite nicht zur Verf�gung steht, bin ich damit einverstanden, dass das gew�nschte Paket mit einer geringeren Bandbreite, jedoch mit dem vereinbarten Inklusiv-Datenvolumen / Monat zur Verff�gung gestellt wird.";

$textTarifVodafoneMobileInternetFlat5 = "Der Wechsel in einen SIMonly Tarif ist w�hrend der Mindestlaufzeit nicht m�glich.";

$textTarifVodafoneMobileInternetFlat72Promo = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Die MobileInternet Flat 7,2 Promo enth�lt unbegrenztes Datenübertragungsvolumen im deutschen Vodafone-Netz. Bis zu einem Datenvolumen von 1 GB steht Ihnen im jeweiligen Abrechnungszeitraum die aktuell maximal verf�gbare Bandbreite von bis zu 7,2 Mbit/s zur Verf�gung, danach max. 64 Kbit/s.";

$textTarifVodafoneMobileInternetFlat216Promo = "Nutzung nur als Endkunde im dafür �blichen Umfang: kein Weiterverkauf, keine überlassung an Dritte; kein Betrieb kommerzieller Dienste. Die MobileInternet Flat 21,6 Promo enth�lt unbegrenztes Datenübertragungsvolumen im deutschen Vodafone-Netz. Bis zu einem Datenvolumen von 3 GB steht Ihnen im jeweiligen Abrechnungszeitraum die aktuell maximal verf�gbare Bandbreite von bis zu 21,6 Mbit/s zur Verf�gung, danach max. 64 Kbit/s.";

$textTarifMIFAPN = "Bei einem MobileInternet-Tarif oder einer MobileInternet-Option gilt Ihr Inklusiv-Volumen nur für den APN web.vodafone.de und nur im deutschen Vodafone-Mobilfunknetz.";

$textDienstZuhauseFlatrate1 = "Die Mindestlaufzeit betr�gt 3 Monate. Die K�ndigungsfrist betr�gt 2 Wochen. Die Option ist erstmalig zum Ablauf der Mindestlaufzeit k�ndbar. Wird die Option nicht rechtzeitig gek�ndigt, verl�ngert sich die Option jeweils automatisch um drei Monate. Bei Buchung mit Vodafone KombiComfort filt im Hinblick auf die Mindestlaufzeit der Tarifoption abweichend: DIe Mindestlaufzeit betr�gt 24 Monate. Die K�ndigungsfrist betr�gt 3 Monate. Die Option ist erstmalig zum Ende der Mindestlaufzeit k�ndbar. Wird die Option nicht rechtzeitig gek�ndigt, verl�ngert sie sich geweils automatisch um 12 Monate. Die Tarifoption endet automatisch mit Beendigung der Vodafone ZuhauseOption oder des Vodafone-Vertrages über die Hauptkarte.";

$textDienstZuhauseFlatrate2 = "Die Tarifoption Vodafone ZuhauseFlatrate und -HappyInternational gelten nicht für Rufumleitungen und Konferenzverbindungen. Der Kunde darf die Vodafone-Karte ausschlie�lich als Endkunde im dafür  und nur zum Aufbau manuell über das Mobilfunkendger�t gew�hlter Verbindungen nutzen; unzul�ssig ist insbesondere die Nutzung zum Betrieb von Mehrwert- oder Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center-Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationdiesnstleistungen für Dritte, zur Weitervermittlung von mobilfunkteilnehmern im Vodafone-Netz oder in andere netze über die Vodafone-Karte und zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in Abh�ngingkeit von der Dauert der Verbundung Zahlungen oder andere verm�genswerte Gegendienstleistungen Dritter erh�lt (z.B. Verbindungen zu Werbehotlines).";

$textDienstZuhauseOption1 = "Für Verbindugnen mit der Vodafone ZuhauseOption ins dt. Festnetz gilt immer die 60/60 Taktung, auch wenn für Ihren Mobilfunktarif im �brigen eine andere Taktung vereinbart ist.";

$textDienstZuhauseOption2 = "Die Mindestlaufzeit betr�gt 2 Wochen. Die Option ist erstmalig zum Ablauf der Mindwestlaufzeit k�ndbar. Wird die Iotion nicht rechtzeitig gek�ndigt, verl�ngert sich die Option jeweils automatisch um drei Monate. Die Tarifoption endet automatisch mit Beendigung des Vodafone-Vertrages über die Hauptkarte. Abweichend von der Leistungsbeschreibung für Vodafone D2-Dienstleistungen gelten für die \"Vodafone Zuhause-Funktionalit�t\" folgende Vesonderheiten zum Leisuntsumfang:\na) Vodafone D2 teilt dem Kunden zus�tzluich zu seiner Vodafone-Mobilfunknummer eine neue Festnetznummer aus dem Vorwahlbereich zu, der seiner jeweils aktuellen Zuhause-adresse entspricht. Die Zuteilung dieser Festnetznummer erfolgt sp�testens innerhalb von 6 Wochen nach Antrag des Kunden.\nb) Die Nutzung von \"Vodafone Zuhause\" ist r�umlich auf die festgelegte Zuhause-Adresse beschr�nkt. Den ZuhauseBereich wird Vodafone D2 innerhalb von 5 Tagen nach Beauftragung einrichen. Vodafone D2 erfasst bei jeder Verbindung zu Abrechnungszwecken, ob sich der Kunde innerhalb oder au�erhalb des Zuhause Bereichs aufh�lt. Die Abrechnung zu \"Vodafone Zuhause\" -Konditionen wird jeweils durch einen Signalton zu Beginn eines jeden Gespr�ches angezeigt (Die zus�tzliche visuelle Information im Display des Mobiltelefons wird nicht von allen Endger�ten unterst�tz).\nc) Pro Hauptkarte in einem Tarif mit Mindestlaufzeit kann nur eine Karte in einem Tarif \"Vodafone ZuhauseTalk (Zusatz zu Laufzeitvertrag)\" zugebucht werden; die Hauptkarte darf keinem Gro�kundenrahmenvertrag zugeordnet sein und kenier sonstigen Rabattvereinbarung unterliegen.";

$textDienstHappyInternational1 = "Die Tarifoptionen Vodafone ZuhauseFlatrate und -HappyInternational gelten nicht für Rufumleitungen und Konferenzverbindungen. Der Kunde darf die Vodafone-Karte ausschlie�lich als Endkunde im dafür �blichen Umfang und nur zum Aufbau manuell über das Mobilfunkenger�t gew�hlter Verbindungen nutzen; unzul�ssig ist insbesondere die Nutzung zum Betrieb von Mehrwert- oder Massenkommunikationsdiensten (z.B. Faxbroadcastdiensten, Telemarketing- oder Call-Center.Leistungen), zur Erbringung von entgeltlichen oder unentgeltlichen Zusammenschaltungs- oder sonstigen Telekommunikationsdienstleistungen für Dritte, zur WEitervermittlung von Mobilfunkteilnehmern im Vodafone-Netz oder in andere Netze über die Vodafone-Karte und zur Herstellung von Verbindungen, bei denen der Anrufer aufgrund des Anrufs und/oder in abh�ngigkeit von der Dauer der Verbindungs Zahlungem oder ander verm�genswerte Gegenleistungen Dritter erh�lt (z.b. Verbindungen zu Werbehotlines).";

$textDienstHappyInternational2 = "Die Tarifoption Vodafone HappyInternational (\"HappyInternational\") setzt zu jedem Zeitpunkt einen Vodafone-Kundenvertrag einschlie�lich der Tarifoption Vodafone Zuhause Option und Vodafone Zuhause Flatrate oder einen Vodafone Kundenvertrag in einem der Tarife Vodafone SuperFlat, -SuperFlat(SIM Only) oder -Zuhause Talk24 voraus. Die Mindestlaufzeit von happyInternational betr�gt 24 Monate; sofern der Vodafone-Kundenvertrag bei Buchung von HappyInternational eine k�rzere verbleibende Mindestlaufzeit als 24 Monate aufweist, verk�rzt sich die Mindestlaufzeit von HappyInternational au fden gleichen Zeitraum. Wird die Mindestlaufzeit des Vodafone-Kundenvertrages verl�ngert, verl�ngert sich die Mindestlaufzeit von HappyInternational entsprechend. HappyInternational ist erstmalig zum Ende der jeweiligen Mindestlaufzeit k�ndbar. Wird HappyInternational nicht (rechtzeitig) gek�ndigt, verl�ngert es sich jeweils automatisch um ein Jahr.";

$textDienstHappyWochenendeAbend = "Zus�tzlicher monatlicher Paketpreis/Aufpreis gem�� Preisliste für Vodafone-MinutenPakete. Die Mindestlaufzeit der Option betr�gt 3 Monate; die K�ndigungsfrist 2 Wochen. Die Option ist erstamals zum Ende der Mindestlaufzeit k�ndbar. Wird nicht (rechtzeitig) gek�ndigt, verl�ngert sich die Option automatisch jeweils um 1 Monat.";

$textDienstSmsFremdnetzPaket = "Zus�tzlicher monatlicher Paketpreis/Aufpreis gem�� Preisliste für Vodafone-MinutenPakete.";

$textDienstHappyLiveBroadband = "Vertragsbestandteil ist die Tarifoption Happy Live! Broadband. Der monatliche Basispreis erh�ht sich dadurch um 2,50 Euro monatlich gegenüber dem in der Preisliste zum heweiligen gebuchten Tarif ausgewiesenen monatlichen Basispreis. Dies gilt auch im Fall eines oder mehrerer Tarifwechsel nach Tarifoptionen. Die K�ndigungsfrist für die Tarifoption HappyLive! Broadband betr�gt 3 monate, die Mindestlaufzeit 24 Monate, beginnend mit der Unterzeichnung dieses Auftrages. Die Tarifoption ist erstmals zum Ende der Mindestlaufzeit k�ndbar. Wird die Tarifoption nicht (rechtzeitig) gek�ndigt, verl�ngert sie sich jeweils automatisch um einen Monat. Der Erh�hungsbetrag wird auf der Rechnung gesondert ausgewiesen.";

$textDienstMusikPaket = "Mtl. Paketpreis 10 EUR für 10 Music-Downloads und 1 Std. RadioDJ (minutengenaue Abrechnung bei Channel- o. Collectionwechsel u. am Verbindungsende). Nicht genutzte Inklusivleistungen sind jeweils nicht in den Folgemonat übertragbar. Die Dienste sind nur im Vodafone live!-Portal mit f. d. Dienst geeignetem Handy nutzbar. Die Mindestlaufzeit der Tarifoption/des Zusatzdienstes betr�gt 24 Monate, die K�ndigungsfrist 2 Wochen. Die Tarifoption/ der Zusatzdienst ist erstmals zum Ende der Mindestlaufzeit k�ndbar. Wird nicht gek�ndigt, verl�ngert sich die Tarifoption/ der Zusatzdienst jeweils um einen weiteren Monat.";

$textDienstWebContentTime1 = "Bei vorhandener HSDPA-Versorgung und HSDPA f�higem Endger�t ist HSDPA bis 31.07.2007 ohne zus�tzliche Berechnung nutzbar. Danach werden für eine HSDPA-Freischaltung 5,00 EUR/Monat berechnet. Eine Voice-over-IP-Nutzung wird ab dem 08.07.2007 technisch unterbunden.";

$textDienstWebContentTime2 = "Die Mindestvertragslaufzeit der Tarifoption/ des Zusatzdienstes betr�gt 24 Monate, die K�ndigungsfrist 3 Monate. Die Tarifoptio/ der Zusatzdienst ist erstmalig zum Ende der Mindestlaufzeit k�ndbar. Wird nicht gek�ndigt, verl�ngert sich die Tarifoption/ der Zusatzdienst jeweils um ein weiteres Jahr.";

$textDienstStudentenrabatt = "Der Studenten-Vorteil wird nur gew�hrt, sofern und solange die folgenden Voraussetzungen erf�llt sind:\n- Eine aktuelle Legitimationsbescheinigung (= deutsche Immatrikulationsbescheinigung, deutscher Studentenausweis, deutscher Sch�lerausweis einer allgemeinbildenden oder Berufschule, deutscher Wehr- oder Ersatzdienstausweis oder deutscher Ausweis über die Teilnahme an einem freiwilligen sozialen Jahr) wird Vodafone bei Vertragsabschlu� vorgelegt.\n- Das Alter betr�gt maximal 30 Jahre.\n- EIne Lastschrift-Einzugserm�chtigung wird erteilt.\n- Es liegt kein sonstiger mobilfunkvertrag mit Studenten-Konditionen bei einem Mobilfunkanbieter im Vodafone D2-Netz vor.\n- Die Vodafone-Karte darf keinem Gro�kundenrahmenvertrag zugeordnet sein und keiner sonstigen Rabattvereinbarung unterliegen.\nDer Studenten- Vorteil wird für folgende Dauer gew�hrt:\n- Für Wehrpflichtige, Zivildienstleistende und Absolventeneines freiwilligen sozialen Jahres max. 1 Jahr\n- im �brigen solange die oben genannten Voraussetzungen erf�llt bleiben und eine aktuelle Legitimationsbescheinigung j�hrlich vorgelegt wird.\nMir ist bekannt, dass eine automatische Umstellung der Vodafone-Karte in den von mir gew�hlten Ausgangstarif ohne Studenten-Vorteil erfolgt, wenn eine der oben genannten Voraussetzungen nicht vorliegt oder sp�ter entf�llt oder wenn der Vertrag über die Vodafone-karte auf eine andere Person übertragen wird.\nDie Konditionen des Studenten-Vorteils ergeben sich erg�nzend zu der Preisliste für Vodafone-Tarife aus dem Tarif-Flyer Studenten-Rabatt.\n\nLegitimation für Studenten-Rabatt:\n Ort der (Hoch-)Schule/T�tigkeit:   $enti[StudentOrt] \n Geburtsdatum:                       $enti[StudentGeburtsdatum] ";

$text200MB = "Der Kunde darf d. Vodafone-Karte ausschlie�lich als Endkunde im dafür �blichen Umfang und nur für Verbindungen, die manuell über die Hardware aufgebaut werden, nutzen. Eine Weiterver�u�erung sowie unentgeltliche überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzul�ssig. Bis zu einem Datenvolumen von 200 MB im jeweiligen Abrechnungszeitraum wird die jeweils aktuell maximal verf�gbare Bandbreite bereitgestellt, ab 200 MB stehen max. 64 kbit/s zur Verf�gung. Vodafone beh�lt sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuf�hren.";

$textZHFNTarifwechsel = "Tarifwechsel in andere Mobilfunktarife sind ausgeschlossen.";

$textPrivatnutzungKarte = "Sie dürfen als Kunde die Vodafone-Karte ausschlie�lich als Privatkunde im dafür �blichen Umfang und nur für Verbindungen, die manuell über die Hardware aufgebaut werden, nutzen. Eine Weiterver�u�erung sowie unentgeltliche überlassung des Dienstes an Dritte u. d. Nutzung zum Betrieb kommerzieller Dienste sind unzul�ssig. Beim Surfen im deutschen Vodafone-Netz auf http-basierten Internet-Seiten (über die APN wap.vodafone.de und web.vodafone.de.), f�llt ein Preis von 0,19 Euro pro MB an. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf den n�chsten 100 KBBlock auf. Die maximal verf�gbare Bandbreite ist 7,2 MBit/s. Vodafone pr�ft ab Einrichtung des Tarifes w�hrend Ihrer Vertragslaufzeit, ob eine zus�tzliche Datenoption für Ihr Nutzungsverhalten g�nstiger w�re und richtet diese mit einer monatlichen Laufzeit für Sie ein. Vodafone informiert Sie darüber per SMS. Vodafone beh�lt sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuf�hren.";

$textTarifSuper100SMS = "Nutzung nur für manuell über das Endger�t erstellte SMS zul�ssig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 100 SMS hinausgehenden SMS werden gem�� den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifSuper50SMS = "Nutzung nur für manuell über das Endger�t erstellte SMS zul�ssig. Die gewerbliche Nutzung ist ausgeschlossen. Alle über die Inklusivleistung von 50 SMS hinausgehenden SMS werden gem�� den Konditionen des zugrundeliegenden Vertrages abgerechnet.";

$textTarifSuperDatenvolumen = "Die Nutzung des inklusiven Datenvolumens ist nur mit Handy gestattet. Für die Nutzung mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computers gilt das inklusive Datenvolumen nicht, diese wird gem�� ihrem Tarif berechnet.";

$textDienstBILDplusDigital = " Vodafone BILDplus DIGITAL Promo24
� Zugang zu Nachrichten von BILDplus Digital und Bundesliga bei BILD
� 500 MB Highspeed-Volumen zus�tzlich inklusive
� Nach 24 Monaten endet der Zugang zu BILDplus Digital und Bundesliga bei BILD sowie das 500 MB Highspeed-Volumen automatisch
� Inhaltlich verantwortlich für BILDplus Digital und Bundesliga bei Bild Nachrichten und die Applikation selbst ist die Axel Springer AG, es gelten die Bedingungen der Axel Springer AG. Das Angebot erfolgt im Namen und Rechnung von Vodafone";

$textDienstDatenOptionM = "Die Tarifoption hat eine Mindestlaufzeit von 24 Monaten, die aber sp�testens mit der Mindestlaufzeit des zugrunde liegenden Vodafone-Vertrags endet.Das Inklusiv-Datenvolumenbetr�gt 200 MB im jeweiligen Abrechnungszeitraum, bei Nutzung über 200 MB hinaus f�llt ein Preis von 2,50 Euro pro 50 MB-Block an. Die maximal verf�gbare Bandbreite ist 7,2 Mbit/s. Vodafone beh�lt sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuf�hren.Sie dürfen die Tarifoption nur mit Ihrem internetf�higen Handy nutzen. Mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computer dürfen Sie die Tarifoption nicht nutzen. Sie dürfen die Tarifoption nicht für Voice over IP, Instant Messaging und Peer to Peer nutzen. Durch den zugrunde liegenden Vodafone-Vertrag entstehen weitere Kosten.";

$textDienstDatenOptionS = "Die Tarifoption hat eine Mindestlaufzeit von 24 Monaten, die aber sp�testens mit der Mindestlaufzeit des zugrunde liegenden Vodafone-Vertrags endet. Das Inklusiv-Datenvolumenbetr�gt 50 MB im jeweiligen Abrechnungszeitraum, bei Nutzung über 50 MB hinaus f�llt ein Preis von 0,19 Euro pro MB an. Pro Verbindung, mindestens aber nach 24 Stunden, runden wir auf den n�chsten 100 KB-Block auf. Die maximal verf�gbare Bandbreite ist 7,2 Mbit/s. Vodafone pr�ft ab Einrichtung des Tarifes w�hrend Ihrer Vertragslaufzeit, ob eine zus�tzliche Datenoption für Ihr Nutzungsverhalten g�nstiger w�re und richtet diese mit einer monatlichen Laufzeit für Sie ein. Vodafone informiert Sie darüber per SMS. Vodafone beh�lt sich vor, nach 24 h jeweils eine automatische Trennung der Verbindung durchzuf�hren.Sie dürfen die Tarifoption nur mit Ihrem internetf�higen Handy nutzen. Mit einem Computer, einem ans Handy angeschlossenen oder drahtlos verbundenen Computer dürfen Sie die Tarifoption nicht nutzen. Sie dürfen die Tarifoption nicht für Voice over IP, Instant Messaging und Peer to Peer nutzen. Durch den zugrunde liegenden Vodafone-Vertrag entstehen weitere Kosten.";

$textBlackBerryInternet = "Sie haben 50 MB pro Monat für BlackBerry-Internet-Services inklusive. Für Nutzung, die darüber hinaus geht, zahlen Sie 0,49 Euro pro MB.";

$basic100sim1 = "mtl. Paketpreis 14,99 � für 24 Monate, danach mtl. 19,99�. Mindestlaufzeit 24 Monate, einmalige Anschlusskosten 29,99 �.";

$basic100sim2 = "Tarif enth�lt 100 Min. in alle dt. Netze und ins dt. Festnetz sowie 100 SMS in alle dt. Netze. Beim Surfen im dt. Vodafone-Netz steht Ihnen ein Inklusiv-Datenvolumen von 200 MB/Monat (statt regul�r 100 MB) zur Verf�gung. Bei Nutzung bis 200 MB pro Abrechnungszeitraum steht Ihnen eine Bandbreite von bis zu 7,2 MBit/s zur Verf�gung, danach bis zu 64 KBit/s.";

$basic100sim3 = "Für Nutzung über Inklusiv-Leistungen hinaus ggf. weitere Kosten je nach Verbrauch, z. B. Standardgespr�che in dt. Mobilfunknetze 0,29 �/Min. (60/60-Takt) oder 0,19 �/Standard-SMS.";

$basic100sim4 = "Tethering, Voice-over-IP- und Peer-to-Peer-Kommunikation nicht gestattet.";

$basic100sim5 = "Nicht verbrauchte Inklusiv-Leistungen nicht in den Folgemonat übertragbar.";

?>


